window.VIET_DATABASE = [
    // ==========================================
    // LEVEL 1: SIMPLE (生存等級 - 絕對高頻)
    // ==========================================
    
    // --- 問候與禮貌 ---
    { id: 1, level: 'simple', vn: 'Xin chào', phonetic: 'sin chow', cn: '你好', en: 'Hello', example: 'Xin chào, rất vui được gặp bạn. (你好，很高興見到你。)' },
    { id: 2, level: 'simple', vn: 'Cảm ơn', phonetic: 'gahm un', cn: '謝謝', en: 'Thank you', example: 'Cảm ơn vì đã giúp đỡ. (謝謝你的幫忙。)' },
    { id: 3, level: 'simple', vn: 'Xin lỗi', phonetic: 'sin loy', cn: '對不起', en: 'Sorry', example: 'Xin lỗi, tôi đến muộn. (對不起，我遲到了。)' },
    { id: 4, level: 'simple', vn: 'Tạm biệt', phonetic: 'tam byet', cn: '再見', en: 'Goodbye', example: 'Tạm biệt, hẹn gặp lại! (再見，後會有期！)' },
    { id: 5, level: 'simple', vn: 'Vâng / Dạ', phonetic: 'vuhng / za', cn: '是 / 好的 (敬語)', en: 'Yes', example: 'Dạ, em hiểu rồi ạ. (是的，我明白了。)' },
    { id: 6, level: 'simple', vn: 'Không', phonetic: 'khom', cn: '不 / 沒有', en: 'No', example: 'Tôi không biết. (我不知道。)' },
    { id: 7, level: 'simple', vn: 'Có', phonetic: 'gaw', cn: '有 / 是', en: 'Have / Yes', example: 'Tôi có một câu hỏi. (我有一個問題。)' },
    
    // --- 核心代名詞 (越南語最重要的一環) ---
    { id: 8, level: 'simple', vn: 'Tôi', phonetic: 'toy', cn: '我 (通用)', en: 'I / Me', example: 'Tôi là người Đài Loan. (我是台灣人。)' },
    { id: 9, level: 'simple', vn: 'Bạn', phonetic: 'ban', cn: '你 / 朋友', en: 'You / Friend', example: 'Bạn tên là gì? (你叫什麼名字？)' },
    { id: 10, level: 'simple', vn: 'Anh', phonetic: 'ang', cn: '哥哥 (稱呼年長男性)', en: 'Brother / You (man)', example: 'Anh ơi, cho em hỏi. (大哥，請問一下。)' },
    { id: 11, level: 'simple', vn: 'Chị', phonetic: 'chi', cn: '姊姊 (稱呼年長女性)', en: 'Sister / You (woman)', example: 'Chị ấy rất đẹp. (那位姊姊很漂亮。)' },
    { id: 12, level: 'simple', vn: 'Em', phonetic: 'em', cn: '弟妹 (稱呼年幼者)', en: 'Younger sibling', example: 'Em chào anh ạ. (弟弟/妹妹向哥哥問好。)' },
    { id: 13, level: 'simple', vn: 'Ông', phonetic: 'ohm', cn: '爺爺 / 先生', en: 'Grandpa / Mr.', example: 'Ông ấy là giám đốc. (那位先生是經理。)' },
    { id: 14, level: 'simple', vn: 'Bà', phonetic: 'bah', cn: '奶奶 / 女士', en: 'Grandma / Mrs.', example: 'Bà khỏe không? (奶奶身體好嗎？)' },

    // --- 疑問詞 ---
    { id: 15, level: 'simple', vn: 'Cái gì', phonetic: 'gai zi', cn: '什麼', en: 'What', example: 'Đây là cái gì? (這是什麼？)' },
    { id: 16, level: 'simple', vn: 'Ở đâu', phonetic: 'uh dow', cn: '在哪裡', en: 'Where', example: 'Nhà vệ sinh ở đâu? (廁所在哪裡？)' },
    { id: 17, level: 'simple', vn: 'Khi nào', phonetic: 'khi now', cn: '什麼時候', en: 'When', example: 'Khi nào bạn đi? (你什麼時候走？)' },
    { id: 18, level: 'simple', vn: 'Ai', phonetic: 'ai', cn: '誰', en: 'Who', example: 'Cô ấy là ai? (她是誰？)' },
    { id: 19, level: 'simple', vn: 'Tại sao', phonetic: 'tai sao', cn: '為什麼', en: 'Why', example: 'Tại sao bạn buồn? (你為什麼難過？)' },
    { id: 20, level: 'simple', vn: 'Thế nào', phonetic: 'the now', cn: '怎麼樣', en: 'How', example: 'Bạn cảm thấy thế nào? (你覺得怎麼樣？)' },
    { id: 21, level: 'simple', vn: 'Bao nhiêu', phonetic: 'bao new', cn: '多少', en: 'How much', example: 'Cái này bao nhiêu tiền? (這個多少錢？)' },

    // --- 數字 (1-10) ---
    { id: 22, level: 'simple', vn: 'Một', phonetic: 'mote', cn: '一', en: 'One', example: 'Một ly cà phê. (一杯咖啡。)' },
    { id: 23, level: 'simple', vn: 'Hai', phonetic: 'hai', cn: '二', en: 'Two', example: 'Hai người. (兩個人。)' },
    { id: 24, level: 'simple', vn: 'Ba', phonetic: 'bah', cn: '三', en: 'Three', example: 'Ba giờ chiều. (下午三點。)' },
    { id: 25, level: 'simple', vn: 'Bốn', phonetic: 'bone', cn: '四', en: 'Four', example: 'Bốn cái bánh. (四個蛋糕。)' },
    { id: 26, level: 'simple', vn: 'Năm', phonetic: 'nahm', cn: '五', en: 'Five', example: 'Năm năm rồi. (五年了。)' },
    { id: 27, level: 'simple', vn: 'Sáu', phonetic: 'sow', cn: '六', en: 'Six', example: 'Thứ sáu. (星期五 - 越南文週六是第6天)。)' },
    { id: 28, level: 'simple', vn: 'Bảy', phonetic: 'bay', cn: '七', en: 'Seven', example: 'Bảy giờ sáng. (早上七點。)' },
    { id: 29, level: 'simple', vn: 'Tám', phonetic: 'tam', cn: '八', en: 'Eight', example: 'Tám nghìn đồng. (八千盾。)' },
    { id: 30, level: 'simple', vn: 'Chín', phonetic: 'chin', cn: '九', en: 'Nine', example: 'Chín mươi phần trăm. (百分之九十。)' },
    { id: 31, level: 'simple', vn: 'Mười', phonetic: 'muoi', cn: '十', en: 'Ten', example: 'Mười điểm. (十分/滿分。)' },

    // --- 基礎動詞 ---
    { id: 32, level: 'simple', vn: 'Là', phonetic: 'la', cn: '是', en: 'To be (is/am/are)', example: 'Tôi là sinh viên. (我是學生。)' },
    { id: 33, level: 'simple', vn: 'Ăn', phonetic: 'ahn', cn: '吃', en: 'Eat', example: 'Tôi muốn ăn phở. (我想吃河粉。)' },
    { id: 34, level: 'simple', vn: 'Uống', phonetic: 'wung', cn: '喝', en: 'Drink', example: 'Uống bia không? (喝啤酒嗎？)' },
    { id: 35, level: 'simple', vn: 'Đi', phonetic: 'dee', cn: '去 / 走', en: 'Go', example: 'Tôi đi làm. (我去上班。)' },
    { id: 36, level: 'simple', vn: 'Đến', phonetic: 'den', cn: '來 / 到', en: 'Come / Arrive', example: 'Khi nào bạn đến? (你什麼時候到？)' },
    { id: 37, level: 'simple', vn: 'Làm', phonetic: 'lam', cn: '做 / 工作', en: 'Do / Work', example: 'Bạn làm nghề gì? (你做什麼工作？)' },
    { id: 38, level: 'simple', vn: 'Mua', phonetic: 'mua', cn: '買', en: 'Buy', example: 'Tôi muốn mua cái này. (我想買這個。)' },
    { id: 39, level: 'simple', vn: 'Bán', phonetic: 'ban', cn: '賣', en: 'Sell', example: 'Ở đây có bán nước không? (這裡有賣水嗎？)' },
    { id: 40, level: 'simple', vn: 'Thích', phonetic: 'tick', cn: '喜歡', en: 'Like', example: 'Tôi thích Việt Nam. (我喜歡越南。)' },
    { id: 41, level: 'simple', vn: 'Yêu', phonetic: 'ew', cn: '愛', en: 'Love', example: 'Anh yêu em. (我愛你。)' },
    { id: 42, level: 'simple', vn: 'Ngủ', phonetic: 'ngu', cn: '睡覺', en: 'Sleep', example: 'Tôi buồn ngủ quá. (我太想睡了。)' },
    { id: 43, level: 'simple', vn: 'Xem', phonetic: 'sem', cn: '看', en: 'Watch / See', example: 'Xem phim. (看電影。)' },
    { id: 44, level: 'simple', vn: 'Nói', phonetic: 'noy', cn: '說', en: 'Speak', example: 'Vui lòng nói chậm lại. (請說慢一點。)' },
    { id: 45, level: 'simple', vn: 'Nghe', phonetic: 'ngae', cn: '聽', en: 'Listen', example: 'Bạn có nghe thấy không? (你有聽到嗎？)' },
    { id: 46, level: 'simple', vn: 'Hiểu', phonetic: 'hieu', cn: '懂 / 明白', en: 'Understand', example: 'Bạn có hiểu không? (你懂嗎？)' },
    { id: 47, level: 'simple', vn: 'Biết', phonetic: 'biet', cn: '知道', en: 'Know', example: 'Tôi không biết tiếng Việt. (我不會越南文。)' },

    // ==========================================
    // LEVEL 2: BEGINNER (生活基礎 - 食衣住行)
    // ==========================================

    // --- 飲食與食物 ---
    { id: 48, level: 'beginner', vn: 'Cơm', phonetic: 'gum', cn: '飯', en: 'Rice', example: 'Ăn cơm chưa? (吃飯了嗎？)' },
    { id: 49, level: 'beginner', vn: 'Phở', phonetic: 'fuh', cn: '河粉', en: 'Pho', example: 'Một bát phở bò. (一碗牛肉河粉。)' },
    { id: 50, level: 'beginner', vn: 'Bánh mì', phonetic: 'ban mee', cn: '麵包 / 越式法國麵包', en: 'Bread / Banh Mi', example: 'Bánh mì Việt Nam rất ngon. (越南麵包很好吃。)' },
    { id: 51, level: 'beginner', vn: 'Nước', phonetic: 'nuoc', cn: '水', en: 'Water', example: 'Cho tôi một chai nước. (給我一瓶水。)' },
    { id: 52, level: 'beginner', vn: 'Cà phê', phonetic: 'gah fe', cn: '咖啡', en: 'Coffee', example: 'Cà phê sữa đá. (冰煉乳咖啡。)' },
    { id: 53, level: 'beginner', vn: 'Bia', phonetic: 'bia', cn: '啤酒', en: 'Beer', example: 'Uống bia hơi. (喝生啤酒。)' },
    { id: 54, level: 'beginner', vn: 'Thịt', phonetic: 'tit', cn: '肉', en: 'Meat', example: 'Tôi không ăn thịt. (我不吃肉。)' },
    { id: 55, level: 'beginner', vn: 'Rau', phonetic: 'zao', cn: '蔬菜', en: 'Vegetable', example: 'Ăn nhiều rau rất tốt. (多吃蔬菜很好。)' },
    { id: 56, level: 'beginner', vn: 'Ngon', phonetic: 'ngon', cn: '好吃', en: 'Delicious', example: 'Món này rất ngon. (這道菜很好吃。)' },
    { id: 57, level: 'beginner', vn: 'No', phonetic: 'naw', cn: '飽', en: 'Full', example: 'Tôi no rồi. (我飽了。)' },
    { id: 58, level: 'beginner', vn: 'Đói', phonetic: 'doi', cn: '餓', en: 'Hungry', example: 'Bạn có đói không? (你餓嗎？)' },
    { id: 59, level: 'beginner', vn: 'Tính tiền', phonetic: 'tin tien', cn: '結帳 / 買單', en: 'Bill please', example: 'Em ơi, tính tiền! (服務生，買單！)' },

    // --- 時間與日期 ---
    { id: 60, level: 'beginner', vn: 'Hôm nay', phonetic: 'hom nay', cn: '今天', en: 'Today', example: 'Hôm nay là thứ mấy? (今天是星期幾？)' },
    { id: 61, level: 'beginner', vn: 'Hôm qua', phonetic: 'hom kwa', cn: '昨天', en: 'Yesterday', example: 'Hôm qua tôi ở nhà. (昨天我在家。)' },
    { id: 62, level: 'beginner', vn: 'Ngày mai', phonetic: 'ngay mai', cn: '明天', en: 'Tomorrow', example: 'Ngày mai gặp lại. (明天見。)' },
    { id: 63, level: 'beginner', vn: 'Bây giờ', phonetic: 'bay zuh', cn: '現在', en: 'Now', example: 'Bây giờ là mấy giờ? (現在幾點了？)' },
    { id: 64, level: 'beginner', vn: 'Sáng', phonetic: 'sang', cn: '早上', en: 'Morning', example: 'Chào buổi sáng. (早安。)' },
    { id: 65, level: 'beginner', vn: 'Trưa', phonetic: 'chua', cn: '中午', en: 'Noon', example: 'Nghỉ trưa. (午休。)' },
    { id: 66, level: 'beginner', vn: 'Chiều', phonetic: 'chiew', cn: '下午', en: 'Afternoon', example: 'Chiều nay trời mưa. (今天下午下雨。)' },
    { id: 67, level: 'beginner', vn: 'Tối', phonetic: 'toy', cn: '晚上', en: 'Evening', example: 'Ăn tối chưa? (吃晚餐了嗎？)' },
    { id: 68, level: 'beginner', vn: 'Ngày', phonetic: 'ngay', cn: '日 / 天', en: 'Day', example: 'Một ngày tốt lành. (美好的一天。)' },
    { id: 69, level: 'beginner', vn: 'Tháng', phonetic: 'tang', cn: '月', en: 'Month', example: 'Tháng sau tôi đi du lịch. (下個月我去旅遊。)' },
    { id: 70, level: 'beginner', vn: 'Năm', phonetic: 'nahm', cn: '年', en: 'Year', example: 'Chúc mừng năm mới. (新年快樂。)' },

    // --- 地點與交通 ---
    { id: 71, level: 'beginner', vn: 'Nhà', phonetic: 'nya', cn: '家 / 房子', en: 'House / Home', example: 'Tôi đang ở nhà. (我正在家。)' },
    { id: 72, level: 'beginner', vn: 'Đường', phonetic: 'duong', cn: '路 / 街', en: 'Street / Road', example: 'Đường này đi đâu? (這條路去哪裡？)' },
    { id: 73, level: 'beginner', vn: 'Xe máy', phonetic: 'se mai', cn: '機車', en: 'Motorbike', example: 'Ở Việt Nam có nhiều xe máy. (越南有很多機車。)' },
    { id: 74, level: 'beginner', vn: 'Taxi', phonetic: 'taxi', cn: '計程車', en: 'Taxi', example: 'Gọi cho tôi một chiếc taxi. (幫我叫一輛計程車。)' },
    { id: 75, level: 'beginner', vn: 'Sân bay', phonetic: 'sun bay', cn: '機場', en: 'Airport', example: 'Đi ra sân bay. (去機場。)' },
    { id: 76, level: 'beginner', vn: 'Khách sạn', phonetic: 'khach san', cn: '飯店 / 旅館', en: 'Hotel', example: 'Khách sạn này rất đẹp. (這間飯店很漂亮。)' },
    { id: 77, level: 'beginner', vn: 'Nhà vệ sinh', phonetic: 'nya ve sin', cn: '廁所 / 衛生間', en: 'Toilet', example: 'Cho hỏi nhà vệ sinh ở đâu? (請問廁所在哪裡？)' },
    { id: 78, level: 'beginner', vn: 'Cửa hàng', phonetic: 'kua hang', cn: '商店', en: 'Shop', example: 'Cửa hàng tiện lợi. (便利商店。)' },
    { id: 79, level: 'beginner', vn: 'Chợ', phonetic: 'chuh', cn: '市場', en: 'Market', example: 'Đi chợ mua đồ. (去市場買東西。)' },

    // --- 常用形容詞 ---
    { id: 80, level: 'beginner', vn: 'To', phonetic: 'taw', cn: '大', en: 'Big', example: 'Cái này to quá. (這個太大了。)' },
    { id: 81, level: 'beginner', vn: 'Nhỏ', phonetic: 'nyaw', cn: '小', en: 'Small', example: 'Tôi muốn cái nhỏ hơn. (我想要小一點的。)' },
    { id: 82, level: 'beginner', vn: 'Nhiều', phonetic: 'nyew', cn: '多', en: 'Many / Much', example: 'Cảm ơn rất nhiều. (非常感謝。)' },
    { id: 83, level: 'beginner', vn: 'Ít', phonetic: 'it', cn: '少', en: 'Little / Few', example: 'Một ít đường. (一點糖。)' },
    { id: 84, level: 'beginner', vn: 'Đắt', phonetic: 'dat', cn: '貴', en: 'Expensive', example: 'Đắt quá! bớt đi. (太貴了！算便宜點。)' },
    { id: 85, level: 'beginner', vn: 'Rẻ', phonetic: 'rae', cn: '便宜', en: 'Cheap', example: 'Cái này rất rẻ. (這個很便宜。)' },
    { id: 86, level: 'beginner', vn: 'Đẹp', phonetic: 'dep', cn: '漂亮 / 美', en: 'Beautiful', example: 'Phong cảnh rất đẹp. (風景很美。)' },
    { id: 87, level: 'beginner', vn: 'Nóng', phonetic: 'nong', cn: '熱', en: 'Hot', example: 'Hôm nay trời nóng. (今天天氣熱。)' },
    { id: 88, level: 'beginner', vn: 'Lạnh', phonetic: 'lanh', cn: '冷', en: 'Cold', example: 'Mùa đông rất lạnh. (冬天很冷。)' },

    // ==========================================
    // LEVEL 3: INTERMEDIATE (中階 - 社交與工作)
    // ==========================================

    // --- 工作與職業 ---
    { id: 89, level: 'intermediate', vn: 'Công việc', phonetic: 'cong viec', cn: '工作 (名詞)', en: 'Job', example: 'Công việc của bạn là gì? (你的工作是什麼？)' },
    { id: 90, level: 'intermediate', vn: 'Công ty', phonetic: 'cong tea', cn: '公司', en: 'Company', example: 'Tôi làm việc tại công ty này. (我在這家公司工作。)' },
    { id: 91, level: 'intermediate', vn: 'Giám đốc', phonetic: 'zam doc', cn: '經理 / 總監', en: 'Director / Manager', example: 'Ông ấy là giám đốc. (他是經理。)' },
    { id: 92, level: 'intermediate', vn: 'Nhân viên', phonetic: 'nyan vien', cn: '員工 / 職員', en: 'Employee / Staff', example: 'Nhân viên văn phòng. (辦公室職員。)' },
    { id: 93, level: 'intermediate', vn: 'Họp', phonetic: 'hop', cn: '開會', en: 'Meeting', example: 'Chúng tôi đang họp. (我們正在開會。)' },
    { id: 94, level: 'intermediate', vn: 'Hợp đồng', phonetic: 'hop dong', cn: '合約', en: 'Contract', example: 'Ký hợp đồng. (簽合約。)' },
    { id: 95, level: 'intermediate', vn: 'Lương', phonetic: 'luong', cn: '薪水', en: 'Salary', example: 'Lương tháng này. (這個月的薪水。)' },
    
    // --- 感覺與狀態 ---
    { id: 96, level: 'intermediate', vn: 'Vui', phonetic: 'vui', cn: '開心', en: 'Happy', example: 'Tôi rất vui. (我很開心。)' },
    { id: 97, level: 'intermediate', vn: 'Buồn', phonetic: 'buon', cn: '難過 / 無聊', en: 'Sad / Bored', example: 'Đừng buồn nữa. (別難過了。)' },
    { id: 98, level: 'intermediate', vn: 'Mệt', phonetic: 'met', cn: '累', en: 'Tired', example: 'Tôi mệt quá. (我太累了。)' },
    { id: 99, level: 'intermediate', vn: 'Bận', phonetic: 'bun', cn: '忙', en: 'Busy', example: 'Tôi đang bận. (我正忙。)' },
    { id: 100, level: 'intermediate', vn: 'Rảnh', phonetic: 'zanh', cn: '有空 / 閒', en: 'Free', example: 'Khi nào bạn rảnh? (你什麼時候有空？)' },
    { id: 101, level: 'intermediate', vn: 'Khó', phonetic: 'kho', cn: '難', en: 'Difficult', example: 'Tiếng Việt rất khó. (越南文很難。)' },
    { id: 102, level: 'intermediate', vn: 'Dễ', phonetic: 'ze', cn: '簡單 / 容易', en: 'Easy', example: 'Bài này rất dễ. (這題很簡單。)' },
    { id: 103, level: 'intermediate', vn: 'Quan trọng', phonetic: 'kwan chong', cn: '重要', en: 'Important', example: 'Việc này rất quan trọng. (這件事很重要。)' },
    { id: 104, level: 'intermediate', vn: 'Nguy hiểm', phonetic: 'nguy hiem', cn: '危險', en: 'Dangerous', example: 'Cẩn thận, nguy hiểm! (小心，危險！)' },

    // --- 連接詞與副詞 ---
    { id: 105, level: 'intermediate', vn: 'Và', phonetic: 'va', cn: '和 / 與', en: 'And', example: 'Tôi và bạn. (我和你。)' },
    { id: 106, level: 'intermediate', vn: 'Nhưng', phonetic: 'nyung', cn: '但是', en: 'But', example: 'Đẹp nhưng đắt. (漂亮但是貴。)' },
    { id: 107, level: 'intermediate', vn: 'Vì', phonetic: 'vi', cn: '因為', en: 'Because', example: 'Vì trời mưa. (因為下雨。)' },
    { id: 108, level: 'intermediate', vn: 'Nên', phonetic: 'nen', cn: '所以 / 應該', en: 'So / Should', example: 'Tôi mệt nên tôi nghỉ. (我累了所以我休息。)' },
    { id: 109, level: 'intermediate', vn: 'Nếu', phonetic: 'new', cn: '如果', en: 'If', example: 'Nếu bạn thích. (如果你喜歡。)' },
    { id: 110, level: 'intermediate', vn: 'Cũng', phonetic: 'kung', cn: '也', en: 'Also', example: 'Tôi cũng vậy. (我也是。)' },
    { id: 111, level: 'intermediate', vn: 'Rất', phonetic: 'zut', cn: '很 / 非常', en: 'Very', example: 'Rất tốt. (很好。)' },
    { id: 112, level: 'intermediate', vn: 'Đã', phonetic: 'da', cn: '已經 (過去式)', en: 'Already', example: 'Tôi đã ăn rồi. (我已經吃過了。)' },
    { id: 113, level: 'intermediate', vn: 'Đang', phonetic: 'dang', cn: '正在 (進行式)', en: 'Currently', example: 'Tôi đang học. (我正在學習。)' },
    { id: 114, level: 'intermediate', vn: 'Sẽ', phonetic: 'se', cn: '將要 (未來式)', en: 'Will', example: 'Tôi sẽ đi Việt Nam. (我將要去越南。)' },
    
    // --- 實用名詞 ---
    { id: 115, level: 'intermediate', vn: 'Điện thoại', phonetic: 'dien tway', cn: '電話 / 手機', en: 'Phone', example: 'Số điện thoại của bạn là gì? (你的電話號碼是多少？)' },
    { id: 116, level: 'intermediate', vn: 'Tiền', phonetic: 'tien', cn: '錢', en: 'Money', example: 'Tôi hết tiền rồi. (我沒錢了。)' },
    { id: 117, level: 'intermediate', vn: 'Bạn trai', phonetic: 'ban chai', cn: '男朋友', en: 'Boyfriend', example: 'Cô ấy có bạn trai chưa? (她有男朋友了嗎？)' },
    { id: 118, level: 'intermediate', vn: 'Bạn gái', phonetic: 'ban gai', cn: '女朋友', en: 'Girlfriend', example: 'Bạn gái tôi rất hiền. (我女朋友很溫柔。)' },
    { id: 119, level: 'intermediate', vn: 'Vấn đề', phonetic: 'van de', cn: '問題', en: 'Problem', example: 'Không có vấn đề gì. (沒什麼問題。)' },
    { id: 120, level: 'intermediate', vn: 'Ý kiến', phonetic: 'ee kien', cn: '意見', en: 'Opinion', example: 'Bạn có ý kiến gì không? (你有什麼意見嗎？)' },
    
    // ==========================================
    // LEVEL 4 & 5: UPPER & HARD (精選範例)
    // ==========================================
    
    { id: 121, level: 'upper', vn: 'Kinh nghiệm', phonetic: 'kin nghiem', cn: '經驗', en: 'Experience', example: 'Kinh nghiệm làm việc. (工作經驗。)' },
    { id: 122, level: 'upper', vn: 'Thành công', phonetic: 'tanh cong', cn: '成功', en: 'Success', example: 'Thất bại là mẹ thành công. (失敗為成功之母。)' },
    { id: 123, level: 'upper', vn: 'Chính phủ', phonetic: 'chin fu', cn: '政府', en: 'Government', example: 'Chính sách của chính phủ. (政府的政策。)' },
    { id: 124, level: 'upper', vn: 'Môi trường', phonetic: 'moi chuong', cn: '環境', en: 'Environment', example: 'Bảo vệ môi trường. (保護環境。)' },
    { id: 125, level: 'upper', vn: 'Phát triển', phonetic: 'fat chien', cn: '發展', en: 'Develop', example: 'Phát triển kinh tế. (經濟發展。)' },
    
    { id: 126, level: 'hard', vn: 'Đầu tư', phonetic: 'dow tu', cn: '投資', en: 'Invest', example: 'Đầu tư chứng khoán. (投資股票。)' },
    { id: 127, level: 'hard', vn: 'Thương mại', phonetic: 'thuong mai', cn: '貿易', en: 'Trade', example: 'Thương mại quốc tế. (國際貿易。)' },
    { id: 128, level: 'hard', vn: 'Hợp tác', phonetic: 'hop tac', cn: '合作', en: 'Cooperation', example: 'Hợp tác vui vẻ. (合作愉快。)' },
    { id: 129, level: 'hard', vn: 'Sản xuất', phonetic: 'san xuat', cn: '生產', en: 'Production', example: 'Nhà máy sản xuất. (生產工廠。)' },
    { id: 130, level: 'hard', vn: 'Tiềm năng', phonetic: 'tiem nang', cn: '潛力', en: 'Potential', example: 'Khách hàng tiềm năng. (潛在客戶。)' },

    // --- 顏色 (Màu sắc) ---
    { id: 131, level: 'simple', vn: 'Màu đỏ', phonetic: 'mao daw', cn: '紅色', en: 'Red', example: 'Tôi thích màu đỏ. (我喜歡紅色。)' },
    { id: 132, level: 'simple', vn: 'Màu xanh dương', phonetic: 'mao san zuong', cn: '藍色', en: 'Blue', example: 'Biển màu xanh dương. (大海是藍色的。)' },
    { id: 133, level: 'simple', vn: 'Màu xanh lá', phonetic: 'mao san la', cn: '綠色', en: 'Green', example: 'Cây màu xanh lá. (樹是綠色的。)' },
    { id: 134, level: 'simple', vn: 'Màu vàng', phonetic: 'mao vang', cn: '黃色', en: 'Yellow', example: 'Hoa màu vàng. (花是黃色的。)' },
    { id: 135, level: 'simple', vn: 'Màu trắng', phonetic: 'mao chang', cn: '白色', en: 'White', example: 'Áo sơ mi trắng. (白襯衫。)' },
    { id: 136, level: 'simple', vn: 'Màu đen', phonetic: 'mao den', cn: '黑色', en: 'Black', example: 'Cà phê đen. (黑咖啡。)' },

    // --- 星期 (Thứ trong tuần) ---
    { id: 137, level: 'simple', vn: 'Thứ hai', phonetic: 'tu hai', cn: '星期一', en: 'Monday', example: 'Thứ hai tôi đi làm. (週一我去上班。)' },
    { id: 138, level: 'simple', vn: 'Thứ ba', phonetic: 'tu ba', cn: '星期二', en: 'Tuesday', example: 'Hẹn gặp thứ ba. (週二見。)' },
    { id: 139, level: 'simple', vn: 'Thứ tư', phonetic: 'tu tu', cn: '星期三', en: 'Wednesday', example: 'Thứ tư giữa tuần. (週三是週間。)' },
    { id: 140, level: 'simple', vn: 'Thứ năm', phonetic: 'tu nam', cn: '星期四', en: 'Thursday', example: 'Thứ năm tôi bận. (週四我忙。)' },
    { id: 141, level: 'simple', vn: 'Thứ sáu', phonetic: 'tu sao', cn: '星期五', en: 'Friday', example: 'Thứ sáu vui vẻ. (週五快樂。)' },
    { id: 142, level: 'simple', vn: 'Thứ bảy', phonetic: 'tu bay', cn: '星期六', en: 'Saturday', example: 'Cuối tuần là thứ bảy. (週末是週六。)' },
    { id: 143, level: 'simple', vn: 'Chủ nhật', phonetic: 'chu nhat', cn: '星期日', en: 'Sunday', example: 'Chủ nhật nghỉ ngơi. (週日休息。)' },

    // --- 身體部位 (Cơ thể) ---
    { id: 144, level: 'simple', vn: 'Đầu', phonetic: 'dow', cn: '頭', en: 'Head', example: 'Tôi bị đau đầu. (我頭痛。)' },
    { id: 145, level: 'simple', vn: 'Mắt', phonetic: 'mat', cn: '眼睛', en: 'Eye', example: 'Mắt cô ấy đẹp. (她眼睛很美。)' },
    { id: 146, level: 'simple', vn: 'Mũi', phonetic: 'mui', cn: '鼻子', en: 'Nose', example: 'Sổ mũi. (流鼻涕。)' },
    { id: 147, level: 'simple', vn: 'Miệng', phonetic: 'mieng', cn: '嘴巴', en: 'Mouth', example: 'Mở miệng ra. (張開嘴巴。)' },
    { id: 148, level: 'simple', vn: 'Tay', phonetic: 'tai', cn: '手', en: 'Hand', example: 'Rửa tay. (洗手。)' },
    { id: 149, level: 'simple', vn: 'Chân', phonetic: 'chan', cn: '腳 / 腿', en: 'Leg / Foot', example: 'Đau chân. (腳痛。)' },
    { id: 150, level: 'simple', vn: 'Bụng', phonetic: 'bung', cn: '肚子', en: 'Stomach', example: 'Đói bụng quá. (肚子好餓。)' },

// ==========================================
// 擴充包：BEGINNER (生活、衣物、天氣)
// ==========================================

    // --- 衣物 (Quần áo) ---
    { id: 151, level: 'beginner', vn: 'Áo', phonetic: 'ao', cn: '衣服 / 上衣', en: 'Shirt', example: 'Mặc áo vào. (穿上衣服。)' },
    { id: 152, level: 'beginner', vn: 'Quần', phonetic: 'kwan', cn: '褲子', en: 'Trousers', example: 'Cái quần này dài. (這條褲子很長。)' },
    { id: 153, level: 'beginner', vn: 'Váy', phonetic: 'vai', cn: '裙子', en: 'Skirt', example: 'Cô ấy mặc váy. (她穿裙子。)' },
    { id: 154, level: 'beginner', vn: 'Giày', phonetic: 'zai', cn: '鞋子', en: 'Shoes', example: 'Đôi giày mới. (新鞋子。)' },
    { id: 155, level: 'beginner', vn: 'Dép', phonetic: 'zep', cn: '拖鞋', en: 'Slippers', example: 'Đi dép trong nhà. (在家穿拖鞋。)' },
    { id: 156, level: 'beginner', vn: 'Mũ / Nón', phonetic: 'mu / non', cn: '帽子', en: 'Hat', example: 'Đội mũ lên. (戴上帽子。)' },
    { id: 157, level: 'beginner', vn: 'Kính', phonetic: 'kin', cn: '眼鏡', en: 'Glasses', example: 'Đeo kính. (戴眼鏡。)' },

    // --- 居家用品 (Đồ dùng trong nhà) ---
    { id: 158, level: 'beginner', vn: 'Bàn', phonetic: 'ban', cn: '桌子', en: 'Table', example: 'Cái bàn gỗ. (木桌。)' },
    { id: 159, level: 'beginner', vn: 'Ghế', phonetic: 'ghe', cn: '椅子', en: 'Chair', example: 'Ngồi lên ghế. (坐在椅子上。)' },
    { id: 160, level: 'beginner', vn: 'Giường', phonetic: 'zuong', cn: '床', en: 'Bed', example: 'Lên giường ngủ. (上床睡覺。)' },
    { id: 161, level: 'beginner', vn: 'Đèn', phonetic: 'den', cn: '燈', en: 'Lamp', example: 'Tắt đèn. (關燈。)' },
    { id: 162, level: 'beginner', vn: 'Cửa', phonetic: 'kua', cn: '門', en: 'Door', example: 'Đóng cửa lại. (把門關上。)' },
    { id: 163, level: 'beginner', vn: 'Chìa khóa', phonetic: 'chia kwa', cn: '鑰匙', en: 'Key', example: 'Mất chìa khóa. (弄丟鑰匙。)' },
    { id: 164, level: 'beginner', vn: 'Ly / Cốc', phonetic: 'lee / coc', cn: '杯子', en: 'Cup', example: 'Một ly nước. (一杯水。)' },
    { id: 165, level: 'beginner', vn: 'Bát / Chén', phonetic: 'bat / chen', cn: '碗', en: 'Bowl', example: 'Rửa bát. (洗碗。)' },
    { id: 166, level: 'beginner', vn: 'Đũa', phonetic: 'dua', cn: '筷子', en: 'Chopsticks', example: 'Dùng đũa. (用筷子。)' },

    // --- 天氣 (Thời tiết) ---
    { id: 167, level: 'beginner', vn: 'Mưa', phonetic: 'mua', cn: '雨', en: 'Rain', example: 'Trời đang mưa. (正在下雨。)' },
    { id: 168, level: 'beginner', vn: 'Nắng', phonetic: 'nang', cn: '晴 / 陽光', en: 'Sunny', example: 'Trời nắng đẹp. (天氣晴朗。)' },
    { id: 169, level: 'beginner', vn: 'Gió', phonetic: 'zaw', cn: '風', en: 'Wind', example: 'Gió mát quá. (風好涼。)' },
    { id: 170, level: 'beginner', vn: 'Nóng', phonetic: 'nong', cn: '熱', en: 'Hot', example: 'Mùa hè rất nóng. (夏天很熱。)' },
    { id: 171, level: 'beginner', vn: 'Lạnh', phonetic: 'lanh', cn: '冷', en: 'Cold', example: 'Mùa đông lạnh. (冬天冷。)' },
    { id: 172, level: 'beginner', vn: 'Mát', phonetic: 'mat', cn: '涼爽', en: 'Cool', example: 'Trời mát mẻ. (天氣涼爽。)' },

    // --- 常用動作 (Hành động) ---
    { id: 173, level: 'beginner', vn: 'Đứng', phonetic: 'dung', cn: '站', en: 'Stand', example: 'Đứng dậy. (站起來。)' },
    { id: 174, level: 'beginner', vn: 'Ngồi', phonetic: 'ngoi', cn: '坐', en: 'Sit', example: 'Mời ngồi. (請坐。)' },
    { id: 175, level: 'beginner', vn: 'Chạy', phonetic: 'chay', cn: '跑', en: 'Run', example: 'Chạy bộ. (跑步。)' },
    { id: 176, level: 'beginner', vn: 'Cười', phonetic: 'kuoi', cn: '笑', en: 'Smile / Laugh', example: 'Cô ấy hay cười. (她愛笑。)' },
    { id: 177, level: 'beginner', vn: 'Khóc', phonetic: 'khoc', cn: '哭', en: 'Cry', example: 'Đừng khóc nữa. (別哭了。)' },
    { id: 178, level: 'beginner', vn: 'Tìm', phonetic: 'tim', cn: '找', en: 'Find', example: 'Tôi đang tìm ví. (我正在找錢包。)' },
    { id: 179, level: 'beginner', vn: 'Thấy', phonetic: 'thay', cn: '看見', en: 'See', example: 'Tôi thấy rồi. (我看見了。)' },
    { id: 180, level: 'beginner', vn: 'Lấy', phonetic: 'lay', cn: '拿 / 取', en: 'Take', example: 'Lấy cho tôi cái kia. (拿那個給我。)' },

    // --- 常用形容詞 (Tính từ) ---
    { id: 181, level: 'beginner', vn: 'Nhanh', phonetic: 'nyan', cn: '快', en: 'Fast', example: 'Đi nhanh lên. (走快點。)' },
    { id: 182, level: 'beginner', vn: 'Chậm', phonetic: 'cham', cn: '慢', en: 'Slow', example: 'Nói chậm thôi. (說慢一點。)' },
    { id: 183, level: 'beginner', vn: 'Mới', phonetic: 'moi', cn: '新', en: 'New', example: 'Điện thoại mới. (新手機。)' },
    { id: 184, level: 'beginner', vn: 'Cũ', phonetic: 'ku', cn: '舊', en: 'Old', example: 'Xe cũ. (舊車。)' },
    { id: 185, level: 'beginner', vn: 'Đúng', phonetic: 'dung', cn: '對 / 正確', en: 'Correct', example: 'Bạn nói đúng. (你說得對。)' },
    { id: 186, level: 'beginner', vn: 'Sai', phonetic: 'sai', cn: '錯', en: 'Wrong', example: 'Làm sai rồi. (做錯了。)' },
    { id: 187, level: 'beginner', vn: 'Sạch', phonetic: 'sach', cn: '乾淨', en: 'Clean', example: 'Nhà sạch sẽ. (房子很乾淨。)' },
    { id: 188, level: 'beginner', vn: 'Bẩn / Dơ', phonetic: 'ban / zoh', cn: '髒', en: 'Dirty', example: 'Tay bẩn. (手髒。)' },
    { id: 189, level: 'beginner', vn: 'Giỏi', phonetic: 'zoi', cn: '棒 / 厲害', en: 'Good at', example: 'Bạn giỏi quá. (你太厲害了。)' },

// ==========================================
// 擴充包：INTERMEDIATE (感受、社交、狀態)
// ==========================================

    // --- 情感 (Cảm xúc) ---
    { id: 190, level: 'intermediate', vn: 'Sợ', phonetic: 'shoh', cn: '害怕', en: 'Scared', example: 'Tôi sợ ma. (我怕鬼。)' },
    { id: 191, level: 'intermediate', vn: 'Lo lắng', phonetic: 'lo lang', cn: '擔心', en: 'Worried', example: 'Đừng lo lắng. (別擔心。)' },
    { id: 192, level: 'intermediate', vn: 'Ghét', phonetic: 'ghet', cn: '討厭', en: 'Hate', example: 'Tôi ghét nói dối. (我討厭說謊。)' },
    { id: 193, level: 'intermediate', vn: 'Tin', phonetic: 'tin', cn: '相信', en: 'Believe', example: 'Tôi tin bạn. (我相信你。)' },
    { id: 194, level: 'intermediate', vn: 'Nhớ', phonetic: 'nyoh', cn: '記得 / 想念', en: 'Remember / Miss', example: 'Tôi không nhớ. (我不記得了。)' },
    { id: 195, level: 'intermediate', vn: 'Quên', phonetic: 'kwen', cn: '忘記', en: 'Forget', example: 'Đừng quên nhé. (別忘了喔。)' },
    { id: 196, level: 'intermediate', vn: 'Hạnh phúc', phonetic: 'hanh fuk', cn: '幸福', en: 'Happy', example: 'Gia đình hạnh phúc. (幸福的家庭。)' },
    { id: 197, level: 'intermediate', vn: 'Thoải mái', phonetic: 'twai mai', cn: '舒服 / 自在', en: 'Comfortable', example: 'Ghế này ngồi thoải mái. (這椅子坐著很舒服。)' },
    { id: 198, level: 'intermediate', vn: 'Ngạc nhiên', phonetic: 'ngac nyen', cn: '驚訝', en: 'Surprised', example: 'Tôi rất ngạc nhiên. (我很驚訝。)' },

    // --- 健康與醫療 (Sức khỏe) ---
    { id: 199, level: 'intermediate', vn: 'Bệnh', phonetic: 'ben', cn: '生病', en: 'Sick', example: 'Tôi bị bệnh. (我生病了。)' },
    { id: 200, level: 'intermediate', vn: 'Đau', phonetic: 'dow', cn: '痛', en: 'Pain', example: 'Đau bụng. (肚子痛。)' },
    { id: 201, level: 'intermediate', vn: 'Thuốc', phonetic: 'thuoc', cn: '藥', en: 'Medicine', example: 'Uống thuốc. (吃藥。)' },
    { id: 202, level: 'intermediate', vn: 'Bác sĩ', phonetic: 'bac si', cn: '醫生', en: 'Doctor', example: 'Đi gặp bác sĩ. (去看醫生。)' },
    { id: 203, level: 'intermediate', vn: 'Bệnh viện', phonetic: 'ben vien', cn: '醫院', en: 'Hospital', example: 'Đến bệnh viện. (去醫院。)' },
    { id: 204, level: 'intermediate', vn: 'Khỏe', phonetic: 'kwe', cn: '健康 / 好', en: 'Healthy', example: 'Sức khỏe tốt. (身體健康。)' },

    // --- 動詞進階 (Động từ) ---
    { id: 205, level: 'intermediate', vn: 'Gửi', phonetic: 'gui', cn: '寄 / 送', en: 'Send', example: 'Gửi tin nhắn. (傳訊息。)' },
    { id: 206, level: 'intermediate', vn: 'Nhận', phonetic: 'nyan', cn: '收到 / 領取', en: 'Receive', example: 'Nhận quà. (收禮物。)' },
    { id: 207, level: 'intermediate', vn: 'Mở', phonetic: 'moh', cn: '開', en: 'Open', example: 'Mở cửa ra. (把門打開。)' },
    { id: 208, level: 'intermediate', vn: 'Đóng', phonetic: 'dong', cn: '關', en: 'Close', example: 'Đóng cửa lại. (把門關上。)' },
    { id: 209, level: 'intermediate', vn: 'Bắt đầu', phonetic: 'bat dow', cn: '開始', en: 'Start', example: 'Bắt đầu làm việc. (開始工作。)' },
    { id: 210, level: 'intermediate', vn: 'Kết thúc', phonetic: 'ket thuk', cn: '結束', en: 'Finish', example: 'Cuộc họp kết thúc. (會議結束。)' },
    { id: 211, level: 'intermediate', vn: 'Chuẩn bị', phonetic: 'chuan bi', cn: '準備', en: 'Prepare', example: 'Chuẩn bị đi học. (準備去上學。)' },
    { id: 212, level: 'intermediate', vn: 'Giúp', phonetic: 'zup', cn: '幫忙', en: 'Help', example: 'Giúp tôi với. (幫幫我。)' },
    { id: 213, level: 'intermediate', vn: 'Hỏi', phonetic: 'hoi', cn: '問', en: 'Ask', example: 'Tôi muốn hỏi đường. (我想問路。)' },
    { id: 214, level: 'intermediate', vn: 'Trả lời', phonetic: 'cha loi', cn: '回答', en: 'Answer', example: 'Vui lòng trả lời. (請回答。)' },
    { id: 215, level: 'intermediate', vn: 'Sử dụng', phonetic: 'su dung', cn: '使用', en: 'Use', example: 'Cách sử dụng. (使用方法。)' },

    // --- 教育與學習 (Học tập) ---
    { id: 216, level: 'intermediate', vn: 'Học', phonetic: 'hoc', cn: '學', en: 'Study', example: 'Học tiếng Việt. (學越南文。)' },
    { id: 217, level: 'intermediate', vn: 'Thi', phonetic: 'thi', cn: '考試', en: 'Exam', example: 'Ngày mai có bài thi. (明天有考試。)' },
    { id: 218, level: 'intermediate', vn: 'Bài tập', phonetic: 'bai tap', cn: '作業', en: 'Homework', example: 'Làm bài tập về nhà. (做家庭作業。)' },
    { id: 219, level: 'intermediate', vn: 'Câu hỏi', phonetic: 'kaw hoi', cn: '問題', en: 'Question', example: 'Có câu hỏi gì không? (有什麼問題嗎？)' },
    { id: 220, level: 'intermediate', vn: 'Trường học', phonetic: 'chuong hoc', cn: '學校', en: 'School', example: 'Đến trường học. (去學校。)' },
    
    // --- 科技與通訊 (Công nghệ) ---
    { id: 221, level: 'intermediate', vn: 'Máy tính', phonetic: 'mai tin', cn: '電腦', en: 'Computer', example: 'Dùng máy tính. (用電腦。)' },
    { id: 222, level: 'intermediate', vn: 'Mạng', phonetic: 'mang', cn: '網路', en: 'Internet', example: 'Mạng yếu quá. (網路太弱了。)' },
    { id: 223, level: 'intermediate', vn: 'Tin nhắn', phonetic: 'tin nyan', cn: '訊息 / 簡訊', en: 'Message', example: 'Nhắn tin cho tôi. (傳訊息給我。)' },
    { id: 224, level: 'intermediate', vn: 'Gọi điện', phonetic: 'goi dien', cn: '打電話', en: 'Call', example: 'Gọi điện thoại. (打電話。)' },
    { id: 225, level: 'intermediate', vn: 'Ảnh', phonetic: 'anh', cn: '照片', en: 'Photo', example: 'Chụp ảnh. (拍照。)' },
    { id: 226, level: 'intermediate', vn: 'Video', phonetic: 'vi de o', cn: '影片', en: 'Video', example: 'Xem video. (看影片。)' },

    // --- 時間頻率 (Tần suất) ---
    { id: 227, level: 'intermediate', vn: 'Luôn luôn', phonetic: 'luon luon', cn: '總是', en: 'Always', example: 'Anh ấy luôn đi sớm. (他總是早到。)' },
    { id: 228, level: 'intermediate', vn: 'Thường xuyên', phonetic: 'thuong swen', cn: '經常', en: 'Often', example: 'Tôi thường xuyên uống cà phê. (我經常喝咖啡。)' },
    { id: 229, level: 'intermediate', vn: 'Thỉnh thoảng', phonetic: 'thin twang', cn: '有時候', en: 'Sometimes', example: 'Thỉnh thoảng tôi đi xem phim. (有時候我去看電影。)' },
    { id: 230, level: 'intermediate', vn: 'Hiếm khi', phonetic: 'hiem khi', cn: '很少 / 難得', en: 'Rarely', example: 'Hiếm khi gặp lại. (難得再見。)' },
    { id: 231, level: 'intermediate', vn: 'Chưa bao giờ', phonetic: 'chua bao zoh', cn: '從未', en: 'Never', example: 'Tôi chưa bao giờ ăn món này. (我從未吃過這道菜。)' },
    
    // --- 方位 (Phương hướng) ---
    { id: 232, level: 'intermediate', vn: 'Trái', phonetic: 'chai', cn: '左', en: 'Left', example: 'Rẽ trái. (左轉。)' },
    { id: 233, level: 'intermediate', vn: 'Phải', phonetic: 'fai', cn: '右 / 對', en: 'Right', example: 'Rẽ phải. (右轉。)' },
    { id: 234, level: 'intermediate', vn: 'Trên', phonetic: 'chen', cn: '上', en: 'Up / On', example: 'Ở trên bàn. (在桌上。)' },
    { id: 235, level: 'intermediate', vn: 'Dưới', phonetic: 'zuoi', cn: '下', en: 'Down / Under', example: 'Ở dưới ghế. (在椅子下。)' },
    { id: 236, level: 'intermediate', vn: 'Trong', phonetic: 'chong', cn: '裡', en: 'In', example: 'Ở trong nhà. (在家裡。)' },
    { id: 237, level: 'intermediate', vn: 'Ngoài', phonetic: 'ngoai', cn: '外', en: 'Out', example: 'Đi ra ngoài. (出去外面。)' },
    { id: 238, level: 'intermediate', vn: 'Trước', phonetic: 'chuoc', cn: '前', en: 'Before / Front', example: 'Phía trước. (前面。)' },
    { id: 239, level: 'intermediate', vn: 'Sau', phonetic: 'sao', cn: '後', en: 'After / Back', example: 'Phía sau. (後面。)' },
    { id: 240, level: 'intermediate', vn: 'Gần', phonetic: 'gan', cn: '近', en: 'Near', example: 'Nhà tôi gần đây. (我家在附近。)' },
    { id: 241, level: 'intermediate', vn: 'Xa', phonetic: 'sa', cn: '遠', en: 'Far', example: 'Đi rất xa. (走很遠。)' },

    // --- 動物 (Động vật) ---
    { id: 242, level: 'simple', vn: 'Con chó', phonetic: 'gon cho', cn: '狗', en: 'Dog', example: 'Nhà tôi có nuôi chó. (我家有養狗。)' },
    { id: 243, level: 'simple', vn: 'Con mèo', phonetic: 'gon meo', cn: '貓', en: 'Cat', example: 'Con mèo đang ngủ. (貓正在睡覺。)' },
    { id: 244, level: 'simple', vn: 'Con gà', phonetic: 'gon ga', cn: '雞', en: 'Chicken', example: 'Gà trống gáy sáng. (公雞晨啼。)' },
    { id: 245, level: 'simple', vn: 'Con vịt', phonetic: 'gon vit', cn: '鴨', en: 'Duck', example: 'Món vịt quay. (烤鴨。)' },
    { id: 246, level: 'simple', vn: 'Con lợn / heo', phonetic: 'gon lon / heo', cn: '豬', en: 'Pig', example: 'Con heo đất. (小豬撲滿。)' },
    { id: 247, level: 'simple', vn: 'Con bò', phonetic: 'gon baw', cn: '牛', en: 'Cow', example: 'Thịt bò rất ngon. (牛肉很好吃。)' },
    { id: 248, level: 'simple', vn: 'Con trâu', phonetic: 'gon chow', cn: '水牛', en: 'Buffalo', example: 'Con trâu đi cày. (水牛耕田。)' },
    { id: 249, level: 'simple', vn: 'Con chim', phonetic: 'gon chim', cn: '鳥', en: 'Bird', example: 'Chim hót líu lo. (鳥兒啾啾叫。)' },
    { id: 250, level: 'simple', vn: 'Con cá', phonetic: 'gon ca', cn: '魚', en: 'Fish', example: 'Cá bơi dưới nước. (魚在水裡游。)' },
    { id: 251, level: 'beginner', vn: 'Con tôm', phonetic: 'gon tom', cn: '蝦', en: 'Shrimp', example: 'Tôm hùm. (龍蝦。)' },
    { id: 252, level: 'beginner', vn: 'Con cua', phonetic: 'gon kua', cn: '螃蟹', en: 'Crab', example: 'Bún riêu cua. (蟹肉米線。)' },
    { id: 253, level: 'beginner', vn: 'Con chuột', phonetic: 'gon chuot', cn: '老鼠', en: 'Mouse', example: 'Mèo bắt chuột. (貓抓老鼠。)' },
    { id: 254, level: 'beginner', vn: 'Con hổ', phonetic: 'gon ho', cn: '老虎', en: 'Tiger', example: 'Hổ là chúa sơn lâm. (老虎是森林之王。)' },
    { id: 255, level: 'beginner', vn: 'Con voi', phonetic: 'gon voi', cn: '大象', en: 'Elephant', example: 'Con voi có cái vòi dài. (大象有長鼻子。)' },
    { id: 256, level: 'beginner', vn: 'Con khỉ', phonetic: 'gon khi', cn: '猴子', en: 'Monkey', example: 'Khỉ leo cây. (猴子爬樹。)' },
    { id: 257, level: 'beginner', vn: 'Con ngựa', phonetic: 'gon ngua', cn: '馬', en: 'Horse', example: 'Cưỡi ngựa. (騎馬。)' },
    { id: 258, level: 'beginner', vn: 'Con thỏ', phonetic: 'gon tho', cn: '兔子', en: 'Rabbit', example: 'Con thỏ ăn cà rốt. (兔子吃紅蘿蔔。)' },
    { id: 259, level: 'beginner', vn: 'Con muỗi', phonetic: 'gon muoi', cn: '蚊子', en: 'Mosquito', example: 'Bị muỗi đốt. (被蚊子叮。)' },
    { id: 260, level: 'beginner', vn: 'Con ong', phonetic: 'gon ong', cn: '蜜蜂', en: 'Bee', example: 'Ong làm mật. (蜜蜂釀蜜。)' },
    { id: 261, level: 'beginner', vn: 'Con bướm', phonetic: 'gon buom', cn: '蝴蝶', en: 'Butterfly', example: 'Bướm bay lượn. (蝴蝶飛舞。)' },

    // --- 水果 (Trái cây) ---
    { id: 262, level: 'simple', vn: 'Táo', phonetic: 'tao', cn: '蘋果', en: 'Apple', example: 'Ăn một quả táo. (吃一顆蘋果。)' },
    { id: 263, level: 'simple', vn: 'Chuối', phonetic: 'chuoi', cn: '香蕉', en: 'Banana', example: 'Nải chuối chín. (熟香蕉。)' },
    { id: 264, level: 'simple', vn: 'Cam', phonetic: 'kam', cn: '柳橙 / 橘子', en: 'Orange', example: 'Nước cam vắt. (現榨柳橙汁。)' },
    { id: 265, level: 'beginner', vn: 'Dưa hấu', phonetic: 'zua how', cn: '西瓜', en: 'Watermelon', example: 'Dưa hấu đỏ ngọt. (紅西瓜很甜。)' },
    { id: 266, level: 'beginner', vn: 'Xoài', phonetic: 'swai', cn: '芒果', en: 'Mango', example: 'Xoài cát. (一種好吃的芒果品種。)' },
    { id: 267, level: 'beginner', vn: 'Dâu tây', phonetic: 'zow tay', cn: '草莓', en: 'Strawberry', example: 'Sinh tố dâu. (草莓冰沙。)' },
    { id: 268, level: 'beginner', vn: 'Dứa / Thơm', phonetic: 'zua / thom', cn: '鳳梨', en: 'Pineapple', example: 'Quả dứa gai. (鳳梨。)' },
    { id: 269, level: 'beginner', vn: 'Dừa', phonetic: 'zua', cn: '椰子', en: 'Coconut', example: 'Uống nước dừa. (喝椰子水。)' },
    { id: 270, level: 'beginner', vn: 'Chanh', phonetic: 'chan', cn: '檸檬', en: 'Lemon', example: 'Trà chanh. (檸檬茶。)' },
    { id: 271, level: 'beginner', vn: 'Bơ', phonetic: 'boh', cn: '酪梨 / 奶油', en: 'Avocado / Butter', example: 'Sinh tố bơ. (酪梨牛奶。)' },
    { id: 272, level: 'beginner', vn: 'Sầu riêng', phonetic: 'sau rieng', cn: '榴槤', en: 'Durian', example: 'Mùi sầu riêng. (榴槤的味道。)' },
    { id: 273, level: 'beginner', vn: 'Nho', phonetic: 'nyo', cn: '葡萄', en: 'Grape', example: 'Chùm nho tím. (一串紫葡萄。)' },
    { id: 274, level: 'beginner', vn: 'Đu đủ', phonetic: 'du du', cn: '木瓜', en: 'Papaya', example: 'Gỏi đu đủ. (涼拌木瓜絲。)' },
    { id: 275, level: 'beginner', vn: 'Ổi', phonetic: 'oi', cn: '芭樂', en: 'Guava', example: 'Nước ép ổi. (芭樂汁。)' },
    { id: 276, level: 'beginner', vn: 'Vải', phonetic: 'vai', cn: '荔枝', en: 'Lychee', example: 'Vải thiều. (荔枝。)' },
    { id: 277, level: 'beginner', vn: 'Thanh long', phonetic: 'thanh long', cn: '火龍果', en: 'Dragon fruit', example: 'Thanh long ruột đỏ. (紅肉火龍果。)' },

    // --- 蔬菜與辛香料 (Rau củ) ---
    { id: 278, level: 'beginner', vn: 'Cà chua', phonetic: 'ca chua', cn: '番茄', en: 'Tomato', example: 'Sốt cà chua. (番茄醬。)' },
    { id: 279, level: 'beginner', vn: 'Khoai tây', phonetic: 'kwai tay', cn: '馬鈴薯', en: 'Potato', example: 'Khoai tây chiên. (炸薯條。)' },
    { id: 280, level: 'beginner', vn: 'Hành', phonetic: 'hanh', cn: '洋蔥 / 蔥', en: 'Onion', example: 'Hành tây. (洋蔥。)' },
    { id: 281, level: 'beginner', vn: 'Tỏi', phonetic: 'toi', cn: '大蒜', en: 'Garlic', example: 'Phi tỏi thơm. (爆香大蒜。)' },
    { id: 282, level: 'beginner', vn: 'Ớt', phonetic: 'ot', cn: '辣椒', en: 'Chili', example: 'Cay quá, nhiều ớt. (太辣了，很多辣椒。)' },
    { id: 283, level: 'beginner', vn: 'Cà rốt', phonetic: 'ca rot', cn: '紅蘿蔔', en: 'Carrot', example: 'Nước ép cà rốt. (紅蘿蔔汁。)' },
    { id: 284, level: 'beginner', vn: 'Dưa leo', phonetic: 'zua leo', cn: '小黃瓜', en: 'Cucumber', example: 'Dưa leo giòn. (脆小黃瓜。)' },
    { id: 285, level: 'beginner', vn: 'Nấm', phonetic: 'nam', cn: '蘑菇', en: 'Mushroom', example: 'Lẩu nấm. (蘑菇火鍋。)' },
    { id: 286, level: 'beginner', vn: 'Rau muống', phonetic: 'zao muong', cn: '空心菜', en: 'Water spinach', example: 'Rau muống xào tỏi. (空心菜炒大蒜 - 越南名菜。)' },

    // --- 大自然 (Thiên nhiên) ---
    { id: 287, level: 'simple', vn: 'Mặt trời', phonetic: 'mat choi', cn: '太陽', en: 'Sun', example: 'Mặt trời mọc. (日出。)' },
    { id: 288, level: 'simple', vn: 'Mặt trăng', phonetic: 'mat chang', cn: '月亮', en: 'Moon', example: 'Ngắm trăng. (賞月。)' },
    { id: 289, level: 'beginner', vn: 'Sao', phonetic: 'sao', cn: '星星', en: 'Star', example: 'Ngôi sao sáng. (明亮的星星。)' },
    { id: 290, level: 'beginner', vn: 'Trời', phonetic: 'choi', cn: '天 / 天空', en: 'Sky', example: 'Ông trời. (老天爺。)' },
    { id: 291, level: 'beginner', vn: 'Mây', phonetic: 'may', cn: '雲', en: 'Cloud', example: 'Mây trắng bay. (白雲飄。)' },
    { id: 292, level: 'beginner', vn: 'Biển', phonetic: 'bien', cn: '海', en: 'Sea', example: 'Đi tắm biển. (去海邊游泳。)' },
    { id: 293, level: 'beginner', vn: 'Núi', phonetic: 'nui', cn: '山', en: 'Mountain', example: 'Leo núi. (爬山。)' },
    { id: 294, level: 'beginner', vn: 'Sông', phonetic: 'song', cn: '河', en: 'River', example: 'Sông Mê Kông. (湄公河。)' },
    { id: 295, level: 'beginner', vn: 'Hồ', phonetic: 'ho', cn: '湖', en: 'Lake', example: 'Hồ Hoàn Kiếm. (還劍湖。)' },
    { id: 296, level: 'beginner', vn: 'Cây', phonetic: 'kay', cn: '樹', en: 'Tree', example: 'Trồng cây. (種樹。)' },
    { id: 297, level: 'beginner', vn: 'Hoa', phonetic: 'hwa', cn: '花', en: 'Flower', example: 'Hoa hồng. (玫瑰花。)' },
    { id: 298, level: 'beginner', vn: 'Cỏ', phonetic: 'kaw', cn: '草', en: 'Grass', example: 'Bãi cỏ xanh. (綠草地。)' },

// ==========================================
// 擴充包 Part 3：BEGINNER/INTERMEDIATE (生活動作、地點、狀態)
// ==========================================

    // --- 日常動作 (Hoạt động hàng ngày) ---
    { id: 299, level: 'beginner', vn: 'Thức dậy', phonetic: 'thuc zay', cn: '起床', en: 'Wake up', example: 'Tôi thức dậy lúc 6 giờ. (我6點起床。)' },
    { id: 300, level: 'beginner', vn: 'Rửa mặt', phonetic: 'rua mat', cn: '洗臉', en: 'Wash face', example: 'Rửa mặt bằng nước ấm. (用溫水洗臉。)' },
    { id: 301, level: 'beginner', vn: 'Đánh răng', phonetic: 'danh rang', cn: '刷牙', en: 'Brush teeth', example: 'Đánh răng buổi tối. (晚上刷牙。)' },
    { id: 302, level: 'beginner', vn: 'Tắm', phonetic: 'tam', cn: '洗澡', en: 'Shower', example: 'Đi tắm đi. (去洗澡吧。)' },
    { id: 303, level: 'beginner', vn: 'Thay quần áo', phonetic: 'thay kwan ao', cn: '換衣服', en: 'Change clothes', example: 'Thay quần áo đẹp. (換漂亮的衣服。)' },
    { id: 304, level: 'beginner', vn: 'Ăn sáng', phonetic: 'an sang', cn: '吃早餐', en: 'Eat breakfast', example: 'Ăn sáng chưa? (吃早餐了嗎？)' },
    { id: 305, level: 'beginner', vn: 'Đi học', phonetic: 'di hoc', cn: '去上學', en: 'Go to school', example: 'Học sinh đi học. (學生去上學。)' },
    { id: 306, level: 'beginner', vn: 'Đi làm', phonetic: 'di lam', cn: '去上班', en: 'Go to work', example: 'Tôi đi làm bằng xe máy. (我騎機車上班。)' },
    { id: 307, level: 'beginner', vn: 'Nấu ăn', phonetic: 'nau an', cn: '煮飯 / 烹飪', en: 'Cook', example: 'Mẹ tôi nấu ăn rất ngon. (我媽媽很會煮飯。)' },
    { id: 308, level: 'beginner', vn: 'Dọn dẹp', phonetic: 'zon zep', cn: '打掃 / 整理', en: 'Clean up', example: 'Dọn dẹp nhà cửa. (打掃房子。)' },
    { id: 309, level: 'beginner', vn: 'Giặt đồ', phonetic: 'zat do', cn: '洗衣服', en: 'Wash clothes', example: 'Máy giặt đồ. (洗衣機。)' },
    { id: 310, level: 'beginner', vn: 'Xem tivi', phonetic: 'sem ti vi', cn: '看電視', en: 'Watch TV', example: 'Cả nhà xem tivi. (全家看電視。)' },
    { id: 311, level: 'beginner', vn: 'Nghe nhạc', phonetic: 'nghe nyac', cn: '聽音樂', en: 'Listen to music', example: 'Thích nghe nhạc Pop. (喜歡聽流行樂。)' },
    { id: 312, level: 'beginner', vn: 'Đọc sách', phonetic: 'doc sach', cn: '看書', en: 'Read book', example: 'Đọc sách ở thư viện. (在圖書館看書。)' },
    { id: 313, level: 'beginner', vn: 'Nghỉ ngơi', phonetic: 'nghi ngoi', cn: '休息', en: 'Rest', example: 'Cần nghỉ ngơi nhiều hơn. (需要多休息。)' },
    { id: 314, level: 'beginner', vn: 'Tập thể dục', phonetic: 'tap the duc', cn: '運動', en: 'Exercise', example: 'Tập thể dục buổi sáng. (晨間運動。)' },
    { id: 315, level: 'beginner', vn: 'Đi bộ', phonetic: 'di bo', cn: '走路 / 散步', en: 'Walk', example: 'Đi bộ trong công viên. (在公園散步。)' },
    { id: 316, level: 'beginner', vn: 'Bơi', phonetic: 'boi', cn: '游泳', en: 'Swim', example: 'Hồ bơi. (游泳池。)' },
    { id: 317, level: 'beginner', vn: 'Hát', phonetic: 'hat', cn: '唱歌', en: 'Sing', example: 'Hát Karaoke. (唱卡拉OK。)' },
    { id: 318, level: 'beginner', vn: 'Chơi', phonetic: 'choi', cn: '玩', en: 'Play', example: 'Đi chơi không? (要出去玩嗎？)' },
    { id: 319, level: 'beginner', vn: 'Viết', phonetic: 'viet', cn: '寫', en: 'Write', example: 'Viết thư. (寫信。)' },
    { id: 320, level: 'beginner', vn: 'Vẽ', phonetic: 've', cn: '畫', en: 'Draw', example: 'Vẽ tranh. (畫畫。)' },

    // --- 城市地點 (Địa điểm) ---
    { id: 321, level: 'intermediate', vn: 'Ngân hàng', phonetic: 'ngan hang', cn: '銀行', en: 'Bank', example: 'Rút tiền ở ngân hàng. (在銀行領錢。)' },
    { id: 322, level: 'intermediate', vn: 'Bưu điện', phonetic: 'buu dien', cn: '郵局', en: 'Post office', example: 'Gửi thư ở bưu điện. (在郵局寄信。)' },
    { id: 323, level: 'intermediate', vn: 'Thư viện', phonetic: 'thu vien', cn: '圖書館', en: 'Library', example: 'Mượn sách thư viện. (借圖書館的書。)' },
    { id: 324, level: 'intermediate', vn: 'Siêu thị', phonetic: 'sieu thi', cn: '超市', en: 'Supermarket', example: 'Đi siêu thị mua đồ. (去超市買東西。)' },
    { id: 325, level: 'intermediate', vn: 'Công viên', phonetic: 'cong vien', cn: '公園', en: 'Park', example: 'Đi dạo công viên. (逛公園。)' },
    { id: 326, level: 'intermediate', vn: 'Hiệu thuốc', phonetic: 'hieu thuoc', cn: '藥局', en: 'Pharmacy', example: 'Mua thuốc cảm. (買感冒藥。)' },
    { id: 327, level: 'intermediate', vn: 'Đồn cảnh sát', phonetic: 'don canh sat', cn: '警察局', en: 'Police station', example: 'Gọi cảnh sát. (叫警察。)' },
    { id: 328, level: 'intermediate', vn: 'Tiệm bánh', phonetic: 'tiem banh', cn: '麵包店', en: 'Bakery', example: 'Bánh mì mới ra lò. (剛出爐的麵包。)' },
    { id: 329, level: 'intermediate', vn: 'Quán cà phê', phonetic: 'kwan ca phe', cn: '咖啡廳', en: 'Cafe', example: 'Hẹn hò ở quán cà phê. (在咖啡廳約會。)' },
    { id: 330, level: 'intermediate', vn: 'Nhà hàng', phonetic: 'nha hang', cn: '餐廳', en: 'Restaurant', example: 'Đặt bàn nhà hàng. (預訂餐廳位子。)' },
    { id: 331, level: 'intermediate', vn: 'Ga tàu', phonetic: 'ga tau', cn: '火車站', en: 'Train station', example: 'Đợi ở ga tàu. (在火車站等。)' },
    { id: 332, level: 'intermediate', vn: 'Trạm xe buýt', phonetic: 'cham se buit', cn: '公車站', en: 'Bus stop', example: 'Bắt xe buýt. (搭公車。)' },

    // --- 形容詞補充 (味道與狀態) ---
    { id: 333, level: 'intermediate', vn: 'Ngọt', phonetic: 'ngot', cn: '甜', en: 'Sweet', example: 'Bánh này ngọt quá. (這蛋糕太甜了。)' },
    { id: 334, level: 'intermediate', vn: 'Chua', phonetic: 'chua', cn: '酸', en: 'Sour', example: 'Chanh rất chua. (檸檬很酸。)' },
    { id: 335, level: 'intermediate', vn: 'Cay', phonetic: 'cay', cn: '辣', en: 'Spicy', example: 'Tôi không ăn cay được. (我不能吃辣。)' },
    { id: 336, level: 'intermediate', vn: 'Mặn', phonetic: 'man', cn: '鹹', en: 'Salty', example: 'Canh hơi mặn. (湯有點鹹。)' },
    { id: 337, level: 'intermediate', vn: 'Đắng', phonetic: 'dang', cn: '苦', en: 'Bitter', example: 'Thuốc đắng. (良藥苦口。)' },
    { id: 338, level: 'intermediate', vn: 'Dễ thương', phonetic: 'ze thuong', cn: '可愛', en: 'Cute', example: 'Em bé dễ thương. (可愛的寶寶。)' },
    { id: 339, level: 'intermediate', vn: 'Tốt bụng', phonetic: 'tot bung', cn: '善良 / 好心', en: 'Kind', example: 'Anh ấy rất tốt bụng. (他很善良。)' },
    { id: 340, level: 'intermediate', vn: 'Lười', phonetic: 'luoi', cn: '懶惰', en: 'Lazy', example: 'Mèo lười. (懶貓。)' },
    { id: 341, level: 'intermediate', vn: 'Chăm chỉ', phonetic: 'cham chi', cn: '勤勞', en: 'Hardworking', example: 'Làm việc chăm chỉ. (勤奮工作。)' },
    { id: 342, level: 'intermediate', vn: 'Nặng', phonetic: 'nang', cn: '重', en: 'Heavy', example: 'Cái túi này nặng. (這袋子很重。)' },
    { id: 343, level: 'intermediate', vn: 'Nhẹ', phonetic: 'nhe', cn: '輕', en: 'Light', example: 'Nhẹ như lông hồng. (輕如鴻毛。)' },
    { id: 344, level: 'intermediate', vn: 'Cứng', phonetic: 'cung', cn: '硬', en: 'Hard', example: 'Đá rất cứng. (石頭很硬。)' },
    { id: 345, level: 'intermediate', vn: 'Mềm', phonetic: 'mem', cn: '軟', en: 'Soft', example: 'Gối mềm. (軟枕頭。)' },
    { id: 346, level: 'intermediate', vn: 'Khô', phonetic: 'kho', cn: '乾', en: 'Dry', example: 'Áo đã khô. (衣服乾了。)' },
    { id: 347, level: 'intermediate', vn: 'Ướt', phonetic: 'uot', cn: '濕', en: 'Wet', example: 'Tóc ướt. (濕頭髮。)' },
    { id: 348, level: 'intermediate', vn: 'Ồn ào', phonetic: 'on ao', cn: '吵鬧', en: 'Noisy', example: 'Đường phố ồn ào. (街道吵鬧。)' },
    { id: 349, level: 'intermediate', vn: 'Yên tĩnh', phonetic: 'yen tinh', cn: '安靜', en: 'Quiet', example: 'Giữ yên tĩnh. (保持安靜。)' },
    { id: 350, level: 'intermediate', vn: 'Sáng', phonetic: 'sang', cn: '亮', en: 'Bright', example: 'Đèn sáng quá. (燈太亮了。)' },
    { id: 351, level: 'intermediate', vn: 'Tối', phonetic: 'toi', cn: '暗', en: 'Dark', example: 'Trời tối rồi. (天黑了。)' },

    // --- 家庭與稱謂 (Gia đình) ---
    { id: 352, level: 'simple', vn: 'Bố / Ba', phonetic: 'bo / ba', cn: '爸爸', en: 'Father', example: 'Bố tôi là bác sĩ. (我爸爸是醫生。)' },
    { id: 353, level: 'simple', vn: 'Mẹ / Má', phonetic: 'me / ma', cn: '媽媽', en: 'Mother', example: 'Mẹ nấu ăn ngon. (媽媽煮飯很好吃。)' },
    { id: 354, level: 'beginner', vn: 'Con trai', phonetic: 'gon chai', cn: '兒子', en: 'Son', example: 'Con trai tôi 5 tuổi. (我兒子5歲。)' },
    { id: 355, level: 'beginner', vn: 'Con gái', phonetic: 'gon gai', cn: '女兒', en: 'Daughter', example: 'Con gái rất ngoan. (女兒很乖。)' },
    { id: 356, level: 'beginner', vn: 'Vợ', phonetic: 'vuh', cn: '老婆 / 妻子', en: 'Wife', example: 'Yêu vợ. (愛老婆。)' },
    { id: 357, level: 'beginner', vn: 'Chồng', phonetic: 'chong', cn: '老公 / 丈夫', en: 'Husband', example: 'Chồng tôi đi làm xa. (我老公去遠方工作。)' },
    { id: 358, level: 'beginner', vn: 'Ông', phonetic: 'ong', cn: '爺爺 / 外公', en: 'Grandfather', example: 'Ông nội. (爺爺。)' },
    { id: 359, level: 'beginner', vn: 'Bà', phonetic: 'ba', cn: '奶奶 / 外婆', en: 'Grandmother', example: 'Bà ngoại. (外婆。)' },
    { id: 360, level: 'beginner', vn: 'Cháu', phonetic: 'chaw', cn: '孫子 / 侄子', en: 'Grandchild / Nephew', example: 'Cháu ngoan bác Hồ. (胡伯伯的好孫子。)' },
    { id: 361, level: 'intermediate', vn: 'Người yêu', phonetic: 'nguoi yew', cn: '愛人 / 情人', en: 'Lover', example: 'Người yêu cũ. (前任。)' },
    { id: 362, level: 'intermediate', vn: 'Họ hàng', phonetic: 'haw hang', cn: '親戚', en: 'Relatives', example: 'Thăm họ hàng. (探望親戚。)' },
    { id: 363, level: 'intermediate', vn: 'Anh trai', phonetic: 'anh chai', cn: '哥哥', en: 'Older brother', example: 'Anh trai tôi cao. (我哥哥很高。)' },
    { id: 364, level: 'intermediate', vn: 'Chị gái', phonetic: 'chi gai', cn: '姊姊', en: 'Older sister', example: 'Chị gái đã kết hôn. (姊姊已經結婚了。)' },
    { id: 365, level: 'intermediate', vn: 'Em trai', phonetic: 'em chai', cn: '弟弟', en: 'Younger brother', example: 'Em trai đang đi học. (弟弟正在上學。)' },
    { id: 366, level: 'intermediate', vn: 'Em gái', phonetic: 'em gai', cn: '妹妹', en: 'Younger sister', example: 'Em gái thích búp bê. (妹妹喜歡洋娃娃。)' },

    // --- 居家與家電 (Nhà cửa & Thiết bị) ---
    { id: 367, level: 'beginner', vn: 'Phòng khách', phonetic: 'fong khach', cn: '客廳', en: 'Living room', example: 'Ngồi ở phòng khách. (坐在客廳。)' },
    { id: 368, level: 'beginner', vn: 'Phòng ngủ', phonetic: 'fong ngu', cn: '臥室', en: 'Bedroom', example: 'Phòng ngủ sạch sẽ. (臥室很乾淨。)' },
    { id: 369, level: 'beginner', vn: 'Nhà bếp', phonetic: 'nya bep', cn: '廚房', en: 'Kitchen', example: 'Nấu ăn trong nhà bếp. (在廚房煮飯。)' },
    { id: 370, level: 'beginner', vn: 'Tủ lạnh', phonetic: 'tu lanh', cn: '冰箱', en: 'Refrigerator', example: 'Mở tủ lạnh. (打開冰箱。)' },
    { id: 371, level: 'beginner', vn: 'Máy lạnh', phonetic: 'mai lanh', cn: '冷氣', en: 'Air conditioner', example: 'Bật máy lạnh. (開冷氣。)' },
    { id: 372, level: 'beginner', vn: 'Quạt', phonetic: 'kwat', cn: '電風扇', en: 'Fan', example: 'Quạt mát quá. (電扇好涼。)' },
    { id: 373, level: 'beginner', vn: 'Tivi', phonetic: 'ti vi', cn: '電視', en: 'TV', example: 'Xem tivi. (看電視。)' },
    { id: 374, level: 'beginner', vn: 'Cửa sổ', phonetic: 'kua so', cn: '窗戶', en: 'Window', example: 'Mở cửa sổ ra. (打開窗戶。)' },
    { id: 375, level: 'beginner', vn: 'Sàn nhà', phonetic: 'san nha', cn: '地板', en: 'Floor', example: 'Lau sàn nhà. (拖地。)' },
    { id: 376, level: 'intermediate', vn: 'Tường', phonetic: 'tuong', cn: '牆壁', en: 'Wall', example: 'Treo tranh lên tường. (掛畫在牆上。)' },
    { id: 377, level: 'intermediate', vn: 'Cầu thang', phonetic: 'kaw thang', cn: '樓梯', en: 'Stairs', example: 'Đi cầu thang bộ. (走樓梯。)' },
    { id: 378, level: 'intermediate', vn: 'Gương', phonetic: 'guong', cn: '鏡子', en: 'Mirror', example: 'Soi gương. (照鏡子。)' },
    { id: 379, level: 'intermediate', vn: 'Gối', phonetic: 'goi', cn: '枕頭', en: 'Pillow', example: 'Gối mềm. (軟枕頭。)' },
    { id: 380, level: 'intermediate', vn: 'Chăn / Mền', phonetic: 'chan / men', cn: '棉被', en: 'Blanket', example: 'Đắp chăn. (蓋棉被。)' },
    { id: 381, level: 'intermediate', vn: 'Nồi', phonetic: 'noi', cn: '鍋子', en: 'Pot', example: 'Nồi cơm điện. (電鍋。)' },
    { id: 382, level: 'intermediate', vn: 'Chảo', phonetic: 'chao', cn: '平底鍋', en: 'Frying pan', example: 'Chảo chống dính. (不沾鍋。)' },
    { id: 383, level: 'intermediate', vn: 'Dao', phonetic: 'zao', cn: '刀子', en: 'Knife', example: 'Dao sắc. (鋒利的刀。)' },
    { id: 384, level: 'intermediate', vn: 'Thớt', phonetic: 'thot', cn: '砧板', en: 'Cutting board', example: 'Cái thớt gỗ. (木砧板。)' },
    { id: 385, level: 'intermediate', vn: 'Thùng rác', phonetic: 'thung rac', cn: '垃圾桶', en: 'Trash can', example: 'Vứt rác vào thùng. (把垃圾丟進桶裡。)' },

    // --- 廚房與調料 (Gia vị & Nguyên liệu) ---
    { id: 386, level: 'beginner', vn: 'Đường', phonetic: 'duong', cn: '糖', en: 'Sugar', example: 'Thêm ít đường. (加一點糖。)' },
    { id: 387, level: 'beginner', vn: 'Muối', phonetic: 'muoi', cn: '鹽', en: 'Salt', example: 'Muối mặn. (鹽很鹹。)' },
    { id: 388, level: 'beginner', vn: 'Nước mắm', phonetic: 'nuoc mam', cn: '魚露', en: 'Fish sauce', example: 'Nước mắm ngon. (好吃的魚露。)' },
    { id: 389, level: 'beginner', vn: 'Tiêu', phonetic: 'tiew', cn: '胡椒', en: 'Pepper', example: 'Rắc tiêu lên. (撒上胡椒。)' },
    { id: 390, level: 'beginner', vn: 'Dầu ăn', phonetic: 'zau an', cn: '食用油', en: 'Cooking oil', example: 'Chiên bằng dầu ăn. (用油炸。)' },
    { id: 391, level: 'beginner', vn: 'Gạo', phonetic: 'gao', cn: '米', en: 'Uncooked rice', example: 'Mua 5kg gạo. (買5公斤米。)' },
    { id: 392, level: 'beginner', vn: 'Trứng', phonetic: 'chung', cn: '蛋', en: 'Egg', example: 'Trứng gà. (雞蛋。)' },
    { id: 393, level: 'beginner', vn: 'Sữa', phonetic: 'sua', cn: '牛奶', en: 'Milk', example: 'Uống sữa tươi. (喝鮮奶。)' },
    { id: 394, level: 'beginner', vn: 'Mì', phonetic: 'mee', cn: '麵', en: 'Noodles', example: 'Mì gói. (泡麵。)' },
    { id: 395, level: 'beginner', vn: 'Bún', phonetic: 'bun', cn: '米線', en: 'Rice vermicelli', example: 'Bún bò Huế. (順化牛肉米線。)' },
    { id: 396, level: 'intermediate', vn: 'Xì dầu / Nước tương', phonetic: 'si dau / nuoc tuong', cn: '醬油', en: 'Soy sauce', example: 'Chấm nước tương. (沾醬油。)' },
    { id: 397, level: 'intermediate', vn: 'Giấm', phonetic: 'zam', cn: '醋', en: 'Vinegar', example: 'Giấm chua. (醋很酸。)' },
    { id: 398, level: 'intermediate', vn: 'Gừng', phonetic: 'gung', cn: '薑', en: 'Ginger', example: 'Trà gừng. (薑茶。)' },
    { id: 399, level: 'intermediate', vn: 'Đậu phụ', phonetic: 'dau fu', cn: '豆腐', en: 'Tofu', example: 'Đậu phụ rán. (炸豆腐。)' },
    { id: 400, level: 'intermediate', vn: 'Hải sản', phonetic: 'hai san', cn: '海鮮', en: 'Seafood', example: 'Nhà hàng hải sản. (海鮮餐廳。)' },

    // --- 交通與旅遊 (Giao thông) ---
    { id: 401, level: 'beginner', vn: 'Xe đạp', phonetic: 'se dap', cn: '腳踏車', en: 'Bicycle', example: 'Đi xe đạp. (騎腳踏車。)' },
    { id: 402, level: 'beginner', vn: 'Xe hơi / Ô tô', phonetic: 'se hoi / o to', cn: '汽車', en: 'Car', example: 'Lái xe hơi. (開車。)' },
    { id: 403, level: 'beginner', vn: 'Máy bay', phonetic: 'mai bay', cn: '飛機', en: 'Airplane', example: 'Vé máy bay. (飛機票。)' },
    { id: 404, level: 'beginner', vn: 'Vé', phonetic: 've', cn: '票', en: 'Ticket', example: 'Mua vé xem phim. (買電影票。)' },
    { id: 405, level: 'beginner', vn: 'Hộ chiếu', phonetic: 'ho chieu', cn: '護照', en: 'Passport', example: 'Xin visa hộ chiếu. (申請護照簽證。)' },
    { id: 406, level: 'beginner', vn: 'Hành lý', phonetic: 'hanh ly', cn: '行李', en: 'Luggage', example: 'Ký gửi hành lý. (托運行李。)' },
    { id: 407, level: 'beginner', vn: 'Bản đồ', phonetic: 'ban do', cn: '地圖', en: 'Map', example: 'Xem bản đồ. (看地圖。)' },
    { id: 408, level: 'intermediate', vn: 'Đèn giao thông', phonetic: 'den zao thong', cn: '紅綠燈', en: 'Traffic light', example: 'Dừng đèn đỏ. (紅燈停。)' },
    { id: 409, level: 'intermediate', vn: 'Kẹt xe / Tắc đường', phonetic: 'ket se / tac duong', cn: '塞車', en: 'Traffic jam', example: 'Đường này hay kẹt xe. (這條路常塞車。)' },
    { id: 410, level: 'intermediate', vn: 'Ngã tư', phonetic: 'nga tu', cn: '十字路口', en: 'Intersection', example: 'Rẽ ở ngã tư. (在十字路口轉彎。)' },
    { id: 411, level: 'intermediate', vn: 'Cầu', phonetic: 'kaw', cn: '橋', en: 'Bridge', example: 'Qua cầu. (過橋。)' },
    { id: 412, level: 'intermediate', vn: 'Xăng', phonetic: 'sang', cn: '汽油', en: 'Gasoline', example: 'Đổ xăng. (加油。)' },
    { id: 413, level: 'intermediate', vn: 'Mũ bảo hiểm', phonetic: 'mu bao hiem', cn: '安全帽', en: 'Helmet', example: 'Đội mũ bảo hiểm. (戴安全帽。)' },
    { id: 414, level: 'intermediate', vn: 'Lái xe', phonetic: 'lai se', cn: '駕駛 / 開車', en: 'Drive', example: 'Lái xe cẩn thận. (小心開車。)' },
    { id: 415, level: 'intermediate', vn: 'Du lịch', phonetic: 'zu lich', cn: '旅遊', en: 'Travel', example: 'Hướng dẫn viên du lịch. (導遊。)' },

    // --- 更多動詞 (Động từ - Phần 2) ---
    { id: 416, level: 'simple', vn: 'Mang', phonetic: 'mang', cn: '帶', en: 'Bring', example: 'Mang theo ô. (帶著傘。)' },
    { id: 417, level: 'simple', vn: 'Cầm', phonetic: 'kam', cn: '拿 / 持', en: 'Hold', example: 'Cầm tay nhau. (手牽手。)' },
    { id: 418, level: 'simple', vn: 'Đợi / Chờ', phonetic: 'doi / cho', cn: '等', en: 'Wait', example: 'Đợi tôi một chút. (等我一下。)' },
    { id: 419, level: 'beginner', vn: 'Mời', phonetic: 'moi', cn: '邀請 / 請', en: 'Invite', example: 'Mời vào. (請進。)' },
    { id: 420, level: 'beginner', vn: 'Gọi', phonetic: 'goi', cn: '叫 / 稱呼', en: 'Call', example: 'Tên tôi gọi là... (我的名字叫...)' },
    { id: 421, level: 'beginner', vn: 'Tặng', phonetic: 'tang', cn: '送 (禮物)', en: 'Give / Donate', example: 'Tặng hoa. (送花。)' },
    { id: 422, level: 'beginner', vn: 'Gặp', phonetic: 'gap', cn: '遇見 / 見面', en: 'Meet', example: 'Hẹn gặp lại. (再見。)' },
    { id: 423, level: 'beginner', vn: 'Hy vọng', phonetic: 'hi vong', cn: '希望', en: 'Hope', example: 'Hy vọng trời không mưa. (希望天不要下雨。)' },
    { id: 424, level: 'beginner', vn: 'Cần', phonetic: 'kan', cn: '需要', en: 'Need', example: 'Tôi cần giúp đỡ. (我需要幫忙。)' },
    { id: 425, level: 'beginner', vn: 'Muốn', phonetic: 'muon', cn: '想要', en: 'Want', example: 'Tôi muốn đi ngủ. (我想去睡覺。)' },
    { id: 426, level: 'intermediate', vn: 'Bán', phonetic: 'ban', cn: '賣', en: 'Sell', example: 'Bán hàng. (賣東西。)' },
    { id: 427, level: 'intermediate', vn: 'Mua', phonetic: 'mua', cn: '買', en: 'Buy', example: 'Đi mua sắm. (去購物。)' },
    { id: 428, level: 'intermediate', vn: 'Trả', phonetic: 'cha', cn: '還 / 付', en: 'Pay / Return', example: 'Trả tiền. (付錢。)' },
    { id: 429, level: 'intermediate', vn: 'Đổi', phonetic: 'doi', cn: '換', en: 'Change', example: 'Đổi tiền. (換錢。)' },
    { id: 430, level: 'intermediate', vn: 'Chọn', phonetic: 'chon', cn: '選擇', en: 'Choose', example: 'Chọn cái này. (選這個。)' },
    { id: 431, level: 'intermediate', vn: 'Thử', phonetic: 'thu', cn: '嘗試 / 試穿', en: 'Try', example: 'Mặc thử áo. (試穿衣服。)' },
    { id: 432, level: 'intermediate', vn: 'Sửa', phonetic: 'sua', cn: '修理 / 修改', en: 'Fix / Repair', example: 'Sửa xe. (修車。)' },
    { id: 433, level: 'intermediate', vn: 'Hỏng', phonetic: 'hong', cn: '壞掉', en: 'Broken', example: 'Xe bị hỏng. (車壞了。)' },
    { id: 434, level: 'intermediate', vn: 'Mất', phonetic: 'mat', cn: '丟失 / 不見', en: 'Lost', example: 'Tôi bị mất ví. (我錢包丟了。)' },
    { id: 435, level: 'intermediate', vn: 'Tìm thấy', phonetic: 'tim thay', cn: '找到', en: 'Found', example: 'Đã tìm thấy chìa khóa. (找到鑰匙了。)' },

    // --- 更多形容詞 (Tính từ - Phần 2) ---
    { id: 436, level: 'simple', vn: 'Thông minh', phonetic: 'thong min', cn: '聰明', en: 'Smart', example: 'Cậu bé thông minh. (聰明的小男孩。)' },
    { id: 437, level: 'simple', vn: 'Trẻ', phonetic: 'che', cn: '年輕', en: 'Young', example: 'Cô ấy còn trẻ. (她還年輕。)' },
    { id: 438, level: 'simple', vn: 'Già', phonetic: 'za', cn: '老', en: 'Old', example: 'Người già. (老人。)' },
    { id: 439, level: 'beginner', vn: 'Giàu', phonetic: 'zaw', cn: '富有', en: 'Rich', example: 'Nhà giàu. (有錢人家。)' },
    { id: 440, level: 'beginner', vn: 'Nghèo', phonetic: 'ngheo', cn: '窮', en: 'Poor', example: 'Người nghèo. (窮人。)' },
    { id: 441, level: 'beginner', vn: 'Cao', phonetic: 'kao', cn: '高', en: 'Tall / High', example: 'Tòa nhà cao tầng. (高樓大廈。)' },
    { id: 442, level: 'beginner', vn: 'Thấp', phonetic: 'thap', cn: '矮 / 低', en: 'Short / Low', example: 'Ghế thấp. (矮凳子。)' },
    { id: 443, level: 'beginner', vn: 'Béo / Mập', phonetic: 'beo / map', cn: '胖', en: 'Fat', example: 'Mèo béo. (胖貓。)' },
    { id: 444, level: 'beginner', vn: 'Gầy / Ốm', phonetic: 'gay / om', cn: '瘦', en: 'Thin', example: 'Dáng người gầy. (身材瘦。)' },
    { id: 445, level: 'beginner', vn: 'Đẹp trai', phonetic: 'dep chai', cn: '帥', en: 'Handsome', example: 'Anh ấy rất đẹp trai. (他很帥。)' },
    { id: 446, level: 'beginner', vn: 'Xinh gái', phonetic: 'sin gai', cn: '漂亮 (女生)', en: 'Pretty', example: 'Cô ấy xinh gái quá. (她好漂亮。)' },
    { id: 447, level: 'intermediate', vn: 'Hài hước', phonetic: 'hai huoc', cn: '幽默', en: 'Funny', example: 'Câu chuyện hài hước. (幽默的故事。)' },
    { id: 448, level: 'intermediate', vn: 'Thân thiện', phonetic: 'than thien', cn: '友善', en: 'Friendly', example: 'Người Việt Nam thân thiện. (越南人很友善。)' },
    { id: 449, level: 'intermediate', vn: 'Nhiệt tình', phonetic: 'nhiet tin', cn: '熱情', en: 'Enthusiastic', example: 'Giúp đỡ nhiệt tình. (熱情幫忙。)' },
    { id: 450, level: 'intermediate', vn: 'Lịch sự', phonetic: 'lich su', cn: '禮貌', en: 'Polite', example: 'Nói chuyện lịch sự. (說話有禮貌。)' },
    { id: 451, level: 'intermediate', vn: 'Cẩn thận', phonetic: 'kan than', cn: '小心 / 仔細', en: 'Careful', example: 'Làm việc cẩn thận. (仔細工作。)' },
    { id: 452, level: 'intermediate', vn: 'Quan trọng', phonetic: 'kwan chong', cn: '重要', en: 'Important', example: 'Việc quan trọng. (重要的事。)' },
    { id: 453, level: 'intermediate', vn: 'Đặc biệt', phonetic: 'dac biet', cn: '特別', en: 'Special', example: 'Món ăn đặc biệt. (特別的菜。)' },
    { id: 454, level: 'intermediate', vn: 'Khác', phonetic: 'khac', cn: '不同 / 其他', en: 'Different / Other', example: 'Ý kiến khác. (其他意見。)' },
    { id: 455, level: 'intermediate', vn: 'Giống', phonetic: 'zong', cn: '像 / 一樣', en: 'Same / Like', example: 'Hai người giống nhau. (兩人很像。)' },

    // --- 身體部位補充 (Cơ thể - Phần 2) ---
    { id: 456, level: 'beginner', vn: 'Răng', phonetic: 'zang', cn: '牙齒', en: 'Teeth', example: 'Đau răng. (牙痛。)' },
    { id: 457, level: 'beginner', vn: 'Tóc', phonetic: 'toc', cn: '頭髮', en: 'Hair', example: 'Cắt tóc. (剪頭髮。)' },
    { id: 458, level: 'beginner', vn: 'Tai', phonetic: 'tai', cn: '耳朵', en: 'Ear', example: 'Đau tai. (耳朵痛。)' },
    { id: 459, level: 'beginner', vn: 'Cổ', phonetic: 'co', cn: '脖子', en: 'Neck', example: 'Đau cổ. (脖子痛。)' },
    { id: 460, level: 'beginner', vn: 'Lưng', phonetic: 'lung', cn: '背', en: 'Back', example: 'Đau lưng. (背痛。)' },
    { id: 461, level: 'intermediate', vn: 'Vai', phonetic: 'vai', cn: '肩膀', en: 'Shoulder', example: 'Vỗ vai. (拍肩膀。)' },
    { id: 462, level: 'intermediate', vn: 'Ngực', phonetic: 'nguc', cn: '胸口', en: 'Chest', example: 'Đau tức ngực. (胸悶。)' },
    { id: 463, level: 'intermediate', vn: 'Tim', phonetic: 'tim', cn: '心臟', en: 'Heart', example: 'Tim đập nhanh. (心跳很快。)' },
    { id: 464, level: 'intermediate', vn: 'Máu', phonetic: 'mau', cn: '血', en: 'Blood', example: 'Chảy máu. (流血。)' },
    { id: 465, level: 'intermediate', vn: 'Da', phonetic: 'za', cn: '皮膚', en: 'Skin', example: 'Da trắng. (白皮膚。)' },

    // --- 辦公與學習 (Văn phòng & Học tập) ---
    { id: 466, level: 'intermediate', vn: 'Bút', phonetic: 'but', cn: '筆', en: 'Pen', example: 'Cho tôi mượn bút. (借我筆。)' },
    { id: 467, level: 'intermediate', vn: 'Giấy', phonetic: 'zay', cn: '紙', en: 'Paper', example: 'Tờ giấy trắng. (白紙。)' },
    { id: 468, level: 'intermediate', vn: 'Vở / Tập', phonetic: 'vo / tap', cn: '筆記本', en: 'Notebook', example: 'Ghi vào vở. (寫在筆記本裡。)' },
    { id: 469, level: 'intermediate', vn: 'Bảng', phonetic: 'bang', cn: '黑板 / 白板', en: 'Board', example: 'Viết lên bảng. (寫在黑板上。)' },
    { id: 470, level: 'intermediate', vn: 'Phòng họp', phonetic: 'fong hop', cn: '會議室', en: 'Meeting room', example: 'Vào phòng họp. (進會議室。)' },
    { id: 471, level: 'intermediate', vn: 'Giám đốc', phonetic: 'zam doc', cn: '總經理', en: 'Director', example: 'Phòng giám đốc. (總經理辦公室。)' },
    { id: 472, level: 'intermediate', vn: 'Thư ký', phonetic: 'thu ky', cn: '秘書', en: 'Secretary', example: 'Cô thư ký. (女秘書。)' },
    { id: 473, level: 'intermediate', vn: 'Đồng nghiệp', phonetic: 'dong nghiep', cn: '同事', en: 'Colleague', example: 'Đồng nghiệp thân thiện. (友善的同事。)' },
    { id: 474, level: 'intermediate', vn: 'Lương', phonetic: 'luong', cn: '薪水', en: 'Salary', example: 'Nhận lương. (領薪水。)' },
    { id: 475, level: 'intermediate', vn: 'Thưởng', phonetic: 'thuong', cn: '獎金', en: 'Bonus', example: 'Tiền thưởng tết. (年終獎金。)' },

    // --- 時間頻率補充 (Thời gian - Phần 2) ---
    { id: 476, level: 'beginner', vn: 'Sáng nay', phonetic: 'sang nay', cn: '今天早上', en: 'This morning', example: 'Sáng nay tôi dậy sớm. (今天早上我早起。)' },
    { id: 477, level: 'beginner', vn: 'Tối qua', phonetic: 'toi kwa', cn: '昨天晚上', en: 'Last night', example: 'Tối qua tôi ngủ muộn. (昨晚我晚睡。)' },
    { id: 478, level: 'beginner', vn: 'Tuần này', phonetic: 'tuan nay', cn: '這週', en: 'This week', example: 'Tuần này tôi bận. (這週我忙。)' },
    { id: 479, level: 'beginner', vn: 'Tháng trước', phonetic: 'thang chuoc', cn: '上個月', en: 'Last month', example: 'Lương tháng trước. (上個月薪水。)' },
    { id: 480, level: 'beginner', vn: 'Năm sau', phonetic: 'nam sao', cn: '明年', en: 'Next year', example: 'Năm sau tôi đi du học. (明年我去留學。)' },
    { id: 481, level: 'intermediate', vn: 'Cuối tuần', phonetic: 'kuoi tuan', cn: '週末', en: 'Weekend', example: 'Cuối tuần vui vẻ. (週末愉快。)' },
    { id: 482, level: 'intermediate', vn: 'Lúc nào', phonetic: 'luc nao', cn: '什麼時候 / 隨時', en: 'When / Anytime', example: 'Lúc nào cũng được. (隨時都可以。)' },
    { id: 483, level: 'intermediate', vn: 'Ngay lập tức', phonetic: 'ngay lap tuc', cn: '立刻 / 馬上', en: 'Immediately', example: 'Đi ngay lập tức. (馬上走。)' },
    { id: 484, level: 'intermediate', vn: 'Sớm', phonetic: 'som', cn: '早', en: 'Early', example: 'Đến sớm. (早到。)' },
    { id: 485, level: 'intermediate', vn: 'Muộn / Trễ', phonetic: 'muon / che', cn: '晚 / 遲', en: 'Late', example: 'Đừng đi muộn. (別遲到。)' },

    // --- 緊急與求助 (Khẩn cấp) ---
    { id: 486, level: 'simple', vn: 'Cứu tôi với', phonetic: 'cuu toi voi', cn: '救命', en: 'Help me', example: 'Cứu tôi với! (救命啊！)' },
    { id: 487, level: 'simple', vn: 'Cẩn thận', phonetic: 'kan than', cn: '小心', en: 'Be careful', example: 'Cẩn thận xe cộ. (小心車輛。)' },
    { id: 488, level: 'simple', vn: 'Dừng lại', phonetic: 'zung lai', cn: '停下來', en: 'Stop', example: 'Dừng lại ngay. (馬上停下來。)' },
    { id: 489, level: 'beginner', vn: 'Cháy', phonetic: 'chay', cn: '火災 / 著火', en: 'Fire', example: 'Có cháy! (失火了！)' },
    { id: 490, level: 'beginner', vn: 'Cướp', phonetic: 'cuop', cn: '搶劫', en: 'Robbery', example: 'Bị cướp giật. (被搶劫。)' },
    { id: 491, level: 'intermediate', vn: 'Báo công an', phonetic: 'bao cong an', cn: '報警', en: 'Call police', example: 'Tôi sẽ báo công an. (我會報警。)' },
    { id: 492, level: 'intermediate', vn: 'Xe cứu thương', phonetic: 'se cuu thuong', cn: '救護車', en: 'Ambulance', example: 'Gọi xe cứu thương. (叫救護車。)' },
    { id: 493, level: 'intermediate', vn: 'Lạc đường', phonetic: 'lac duong', cn: '迷路', en: 'Lost way', example: 'Tôi bị lạc đường. (我迷路了。)' },
    { id: 494, level: 'intermediate', vn: 'Mất ví', phonetic: 'mat vi', cn: '掉錢包', en: 'Lost wallet', example: 'Tôi bị mất ví tiền. (我錢包掉了。)' },
    { id: 495, level: 'intermediate', vn: 'Đau bụng', phonetic: 'dau bung', cn: '肚子痛', en: 'Stomachache', example: 'Ăn bậy đau bụng. (亂吃肚子痛。)' },

    // --- 購物與衣服補充 (Mua sắm) ---
    { id: 496, level: 'beginner', vn: 'Tiền lẻ', phonetic: 'tien le', cn: '零錢', en: 'Small change', example: 'Bạn có tiền lẻ không? (你有零錢嗎？)' },
    { id: 497, level: 'beginner', vn: 'Túi', phonetic: 'tui', cn: '袋子 / 包包', en: 'Bag', example: 'Cho tôi xin cái túi. (給我一個袋子。)' },
    { id: 498, level: 'beginner', vn: 'Ví / Bóp', phonetic: 'vi / bop', cn: '錢包', en: 'Wallet', example: 'Ví da. (皮夾。)' },
    { id: 499, level: 'beginner', vn: 'Đồng hồ', phonetic: 'dong ho', cn: '手錶 / 時鐘', en: 'Watch / Clock', example: 'Đồng hồ đeo tay. (手錶。)' },
    { id: 500, level: 'intermediate', vn: 'Kích cỡ / Size', phonetic: 'kich co', cn: '尺寸', en: 'Size', example: 'Size này hơi chật. (這尺寸有點緊。)' },
    { id: 501, level: 'intermediate', vn: 'Vừa', phonetic: 'vua', cn: '合身 / 剛好', en: 'Fit', example: 'Mặc rất vừa. (穿起來很合身。)' },
    { id: 502, level: 'intermediate', vn: 'Rộng', phonetic: 'zong', cn: '寬 / 鬆', en: 'Loose / Wide', example: 'Áo này rộng quá. (這件衣服太鬆了。)' },
    { id: 503, level: 'intermediate', vn: 'Chật', phonetic: 'chat', cn: '緊 / 窄', en: 'Tight', example: 'Giày hơi chật. (鞋子有點緊。)' },
    { id: 504, level: 'intermediate', vn: 'Khuyến mãi', phonetic: 'khuyen mai', cn: '促銷 / 特價', en: 'Promotion', example: 'Đang có khuyến mãi. (正在促銷。)' },
    { id: 505, level: 'intermediate', vn: 'Hóa đơn', phonetic: 'hoa don', cn: '收據 / 發票', en: 'Receipt / Bill', example: 'Cho tôi xin hóa đơn. (請給我收據。)' },

    // --- 興趣與娛樂 (Sở thích) ---
    { id: 506, level: 'beginner', vn: 'Đá bóng', phonetic: 'da bong', cn: '踢足球', en: 'Play soccer', example: 'Thích đá bóng. (喜歡踢足球。)' },
    { id: 507, level: 'beginner', vn: 'Xem phim', phonetic: 'sem fim', cn: '看電影', en: 'Watch movie', example: 'Đi rạp xem phim. (去戲院看電影。)' },
    { id: 508, level: 'beginner', vn: 'Chụp ảnh', phonetic: 'chup anh', cn: '攝影 / 拍照', en: 'Photography', example: 'Sở thích chụp ảnh. (興趣是攝影。)' },
    { id: 509, level: 'intermediate', vn: 'Du lịch', phonetic: 'zu lich', cn: '旅遊', en: 'Travel', example: 'Đi du lịch vòng quanh thế giới. (環遊世界。)' },
    { id: 510, level: 'intermediate', vn: 'Nấu nướng', phonetic: 'nau nuong', cn: '烹飪', en: 'Cooking', example: 'Học nấu nướng. (學做菜。)' },
    { id: 511, level: 'intermediate', vn: 'Đọc truyện', phonetic: 'doc chuyen', cn: '看小說 / 漫畫', en: 'Read stories', example: 'Đọc truyện tranh. (看漫畫。)' },
    { id: 512, level: 'intermediate', vn: 'Ngủ nướng', phonetic: 'ngu nuong', cn: '賴床', en: 'Sleep in', example: 'Cuối tuần ngủ nướng. (週末賴床。)' },
    { id: 513, level: 'intermediate', vn: 'Câu cá', phonetic: 'kau ca', cn: '釣魚', en: 'Fishing', example: 'Đi câu cá. (去釣魚。)' },
    { id: 514, level: 'intermediate', vn: 'Chơi game', phonetic: 'choi game', cn: '玩遊戲', en: 'Play games', example: 'Chơi game điện thoại. (玩手機遊戲。)' },
    { id: 515, level: 'intermediate', vn: 'Mua sắm', phonetic: 'mua sam', cn: '購物', en: 'Shopping', example: 'Nghiện mua sắm. (購物狂。)' },

    // --- 雜項生活用品 (Đồ dùng khác) ---
    { id: 516, level: 'beginner', vn: 'Dù / Ô', phonetic: 'zu / o', cn: '雨傘', en: 'Umbrella', example: 'Mang theo dù. (帶傘。)' },
    { id: 517, level: 'beginner', vn: 'Kéo', phonetic: 'keo', cn: '剪刀', en: 'Scissors', example: 'Cái kéo sắc. (鋒利的剪刀。)' },
    { id: 518, level: 'beginner', vn: 'Bàn chải', phonetic: 'ban chai', cn: '牙刷 / 刷子', en: 'Brush', example: 'Bàn chải đánh răng. (牙刷。)' },
    { id: 519, level: 'beginner', vn: 'Khăn', phonetic: 'khan', cn: '毛巾 / 圍巾', en: 'Towel / Scarf', example: 'Khăn tắm. (浴巾。)' },
    { id: 520, level: 'beginner', vn: 'Xà phòng', phonetic: 'sa fong', cn: '肥皂', en: 'Soap', example: 'Rửa tay bằng xà phòng. (用肥皂洗手。)' },
    { id: 521, level: 'beginner', vn: 'Dầu gội', phonetic: 'zau goi', cn: '洗髮精', en: 'Shampoo', example: 'Hết dầu gội rồi. (洗髮精沒了。)' },
    { id: 522, level: 'beginner', vn: 'Kem đánh răng', phonetic: 'kem danh rang', cn: '牙膏', en: 'Toothpaste', example: 'Mua kem đánh răng. (買牙膏。)' },
    { id: 523, level: 'beginner', vn: 'Giấy vệ sinh', phonetic: 'zay ve sin', cn: '衛生紙', en: 'Toilet paper', example: 'Hết giấy vệ sinh. (衛生紙用完了。)' },
    { id: 524, level: 'intermediate', vn: 'Sạc pin', phonetic: 'sac pin', cn: '充電器', en: 'Charger', example: 'Cục sạc pin đâu? (充電器在哪？)' },
    { id: 525, level: 'intermediate', vn: 'Tai nghe', phonetic: 'tai nghe', cn: '耳機', en: 'Headphones', example: 'Đeo tai nghe. (戴耳機。)' },

    // --- 更多簡單動詞 (Động từ - Phần 3) ---
    { id: 526, level: 'simple', vn: 'Vào', phonetic: 'vao', cn: '進', en: 'Enter', example: 'Mời vào nhà. (請進屋。)' },
    { id: 527, level: 'simple', vn: 'Ra', phonetic: 'za', cn: '出', en: 'Exit', example: 'Đi ra ngoài. (走出去。)' },
    { id: 528, level: 'simple', vn: 'Lên', phonetic: 'len', cn: '上', en: 'Up', example: 'Lên xe. (上車。)' },
    { id: 529, level: 'simple', vn: 'Xuống', phonetic: 'suong', cn: '下', en: 'Down', example: 'Xuống xe. (下車。)' },
    { id: 530, level: 'beginner', vn: 'Đóng', phonetic: 'dong', cn: '關 / 閉', en: 'Close', example: 'Đóng cửa. (關門。)' },
    { id: 531, level: 'beginner', vn: 'Mở', phonetic: 'mo', cn: '開', en: 'Open', example: 'Mở quà. (拆禮物。)' },
    { id: 532, level: 'beginner', vn: 'Bật', phonetic: 'bat', cn: '開 (電器)', en: 'Turn on', example: 'Bật đèn lên. (開燈。)' },
    { id: 533, level: 'beginner', vn: 'Tắt', phonetic: 'tat', cn: '關 (電器)', en: 'Turn off', example: 'Tắt tivi đi. (把電視關了。)' },
    { id: 534, level: 'beginner', vn: 'Gửi', phonetic: 'gui', cn: '寄 / 傳送', en: 'Send', example: 'Gửi thư. (寄信。)' },
    { id: 535, level: 'beginner', vn: 'Nhận', phonetic: 'nhan', cn: '收', en: 'Receive', example: 'Nhận được chưa? (收到了嗎？)' },
    { id: 536, level: 'beginner', vn: 'Ký', phonetic: 'ky', cn: '簽名', en: 'Sign', example: 'Ký tên vào đây. (在這裡簽名。)' },
    { id: 537, level: 'beginner', vn: 'Hút', phonetic: 'hut', cn: '吸 / 抽', en: 'Smoke / Suck', example: 'Hút thuốc lá. (抽菸。)' },
    { id: 538, level: 'beginner', vn: 'Thở', phonetic: 'tho', cn: '呼吸', en: 'Breathe', example: 'Hít thở sâu. (深呼吸。)' },
    { id: 539, level: 'beginner', vn: 'Nghĩ', phonetic: 'nghi', cn: '想 / 思考', en: 'Think', example: 'Tôi nghĩ là đúng. (我想是對的。)' },
    { id: 540, level: 'beginner', vn: 'Quên', phonetic: 'kwen', cn: '忘記', en: 'Forget', example: 'Tôi quên rồi. (我忘了。)' },

    // --- 更多簡單形容詞 (Tính từ - Phần 3) ---
    { id: 541, level: 'simple', vn: 'Đúng', phonetic: 'dung', cn: '對', en: 'Right', example: 'Làm đúng rồi. (做對了。)' },
    { id: 542, level: 'simple', vn: 'Sai', phonetic: 'sai', cn: '錯', en: 'Wrong', example: 'Số điện thoại sai. (電話號碼錯了。)' },
    { id: 543, level: 'simple', vn: 'Thật', phonetic: 'that', cn: '真', en: 'Real / True', example: 'Sự thật. (真相。)' },
    { id: 544, level: 'simple', vn: 'Giả', phonetic: 'za', cn: '假', en: 'Fake', example: 'Hoa giả. (假花。)' },
    { id: 545, level: 'beginner', vn: 'Sạch', phonetic: 'sach', cn: '乾淨', en: 'Clean', example: 'Nước sạch. (乾淨的水。)' },
    { id: 546, level: 'beginner', vn: 'Bẩn', phonetic: 'ban', cn: '髒', en: 'Dirty', example: 'Quần áo bẩn. (髒衣服。)' },
    { id: 547, level: 'beginner', vn: 'Nhanh', phonetic: 'nyan', cn: '快', en: 'Fast', example: 'Chạy nhanh. (跑得快。)' },
    { id: 548, level: 'beginner', vn: 'Chậm', phonetic: 'cham', cn: '慢', en: 'Slow', example: 'Đi chậm lại. (走慢點。)' },
    { id: 549, level: 'beginner', vn: 'Vui', phonetic: 'vui', cn: '開心', en: 'Happy', example: 'Rất vui. (很開心。)' },
    { id: 550, level: 'beginner', vn: 'Buồn', phonetic: 'buon', cn: '難過', en: 'Sad', example: 'Chuyện buồn. (傷心事。)' },
    { id: 551, level: 'beginner', vn: 'Rảnh', phonetic: 'zanh', cn: '有空', en: 'Free', example: 'Khi nào rảnh? (什麼時候有空？)' }
];
